### ISSUE TITLE
DefaultLwM2mEncoder/Decoder behaviour when working with OPAQUE resource

### ISSUE THREAD

**Issue by shabunin** [eclipse/leshan#1133]
Hello,

I'm using leshan-server-cf 2.0.0-M4 (tried M5 as well) as a maven dependency without server-demo serializers, magic converters, etc.

As a client there is Anjay, which implements old lwm2m spec and string resources there has OPAQUE type.

When I'm running read operation, e.g. on /5/0/1 object, OPAQUE response from device is converted to STRING by DefaultLwm2mDecoder and it's ok - we get the same objects independently from device's lwm2m version.

But it doesn't work in opposite direction: I create LwM2mNode as LwM2mSingleResource.newStringResource(..) and send WriteRequest. Exception is raised:

```text
org.eclipse.leshan.core.node.codec.CodecException: Invalid value type for resource /5/0/1, expected OPAQUE, got STRING
	at org.eclipse.leshan.core.node.codec.LwM2mValueChecker.convertValue(LwM2mValueChecker.java:40)
	at org.eclipse.leshan.core.node.codec.tlv.LwM2mNodeTlvEncoder$InternalEncoder.encodeResource(LwM2mNodeTlvEncoder.java:163)
	at org.eclipse.leshan.core.node.codec.tlv.LwM2mNodeTlvEncoder$InternalEncoder.visit(LwM2mNodeTlvEncoder.java:129)
	at org.eclipse.leshan.core.node.LwM2mSingleResource.accept(LwM2mSingleResource.java:228)
...
```

Shouldn't it behave the same way as Decoder - automatically convert according to device model?

I understand that I can implement it myself, still I'm in doubt because in this case I should do some kind of MagicConverter =)

**Comment by DonSpain** [comment]
hi there. Have your received my last mail to your institute mail?
