### ISSUE TITLE
Leshan null pointer exception when writing JSON data

### ISSUE THREAD

**Issue by MrOneTwo** [eclipse/leshan#1152]
Hello, I'm having problems with Leshan server (it worked previously but our CI fetches the latest Leshan and recently it started throwing and exception):

```
2021-11-15 13:32:20,015 LwM2mModelRepository [DEBUG] Model already exists for object 3313 in version 1.0. Overriding it.
2021-11-15 13:32:20,017 LwM2mModelRepository [DEBUG] Model already exists for object 10251 in version 1.0. Overriding it.
2021-11-15 13:32:20,017 LwM2mModelRepository [DEBUG] Model already exists for object 3311 in version 1.0. Overriding it.
2021-11-15 13:32:20,017 LwM2mModelRepository [DEBUG] Model already exists for object 3338 in version 1.0. Overriding it.
2021-11-15 13:32:20,246 LeshanServer         [INFO] LWM2M server started at coap://0.0.0.0/0.0.0.0:5683 coaps://0.0.0.0/0.0.0.0:5684
2021-11-15 13:32:20,331 LeshanServerDemo     [INFO] Web server started at http://0.0.0.0:8080/.
2021-11-15 13:32:31,761 ClientServlet        [WARN] Unexpected exception
java.lang.NullPointerException: null
	at org.eclipse.leshan.server.demo.servlet.json.JacksonLwM2mNodeDeserializer.deserialize(JacksonLwM2mNodeDeserializer.java:127)
	at org.eclipse.leshan.server.demo.servlet.json.JacksonLwM2mNodeDeserializer.deserialize(JacksonLwM2mNodeDeserializer.java:46)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at org.eclipse.leshan.server.demo.servlet.ClientServlet.extractLwM2mNode(ClientServlet.java:434)
	at org.eclipse.leshan.server.demo.servlet.ClientServlet.doPut(ClientServlet.java:263)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This is the request that results in that exception (URL, body and the response we get):

```
send_command: URL: http://localhost:8080/api/clients/qemu_cortex_m3/34120/0/2?format=TLV&timeout=60, body: {'id': 2, 'value': 2}, response: <Response [500]>
```

This is done via Python's requests module:

```py
    ret = requests.request(method, request_url, json=body, timeout=3)
```

Any idea what changed that it suddenly fails?

**Comment by sbernard31** [comment]
What is the "lastest Leshan" exactly ? 

Anyway recently we change a little bit the REST API of server demo, e.g. in you case now you need to add a type field to you payload. `{'id': 2, 'value': 2, 'type':'integer"}` (I guess this is integer but please just put the right type of your ressource)
 
But keep in mind this API is not really intended to be reused : see https://github.com/eclipse/leshan/wiki/F.A.Q.#could-i-reuse-leshan--demo-
If you face some other break please just use the UI and with your browser webtool just see how the UI use the API.

**Comment by MrOneTwo** [comment]
@sbernard31 The latest Leshan means:

```
wget https://ci.eclipse.org/leshan/job/leshan/lastSuccessfulBuild/artifact/leshan-server-demo.jar
```

I'll test it with the `type` added.

**Comment by MrOneTwo** [comment]
@sbernard31 It works now. Using web GUI and inspecting the requests helped a lot. I didn't think about it before, thank you :)

**Comment by MrOneTwo** [comment]
@sbernard31 It works now. Using web GUI and inspecting the requests helped a lot. I didn't think about it before, thank you :)

**Comment by sbernard31** [comment]
You're welcome :wink:

Could I ask how you are using `leshan-server-demo` ?

**Comment by sbernard31** [comment]
There are some discussions there about having some interoperability tests but maybe this is something where efforts could be communalized. I share the link just in case you want to follow it. : https://github.com/eclipse/wakaama/issues/617

Even if I understand why you are using Leshan demo REST API to do that, this is not really intended to be used like this and so we should maybe go to something more dedicated to that but this is more than just a Leshan question.

**Comment by MrOneTwo** [comment]
@sbernard31 Great, thank you for explaining. I'll gladly read up about this.

Unfortunately we've inherited this setup and it was either fixing it or tearing it down. Thanks to you we went with the latter ;)
