### ISSUE TITLE
Problem with registration of some LwM2M clients after upgrading to leshan-2.0.0-M7

### ISSUE THREAD

**Issue by JaroslawLegierski** [eclipse/leshan#1273]
We noticed that after upgrading to leshan-2.0.0-M7, some devices stopped successfully registering in leshan server. We are observing following error:

`[DEBUG] Invalid request [CON-POST   MID=50791, Token=150001, OptionSet={"Uri-Path":"rd", "Content-Format":"application/link-format", "Uri-Query":["lt=86400","lwm2m=1.1","ep=leshan100"]}, "</1/0>;ver=1.1,</3/0>;ver=1.1"] received on the resource /rd from Identity /78.8.63.187:60815[psk=leshan100]
org.eclipse.leshan.core.link.LinkParseException: Unable to parse link 	
        at org.eclipse.leshan.core.link.lwm2m.DefaultLwM2mLinkParser.parseCoreLinkFormat(DefaultLwM2mLinkParser.java:155)
        at org.eclipse.leshan.server.californium.registration.RegisterResource.handleRegister(RegisterResource.java:146)
        at org.eclipse.leshan.server.californium.registration.RegisterResource.handlePOST(RegisterResource.java:104)
        at org.eclipse.californium.core.CoapResource.handleRequest(CoapResource.java:246)
        at org.eclipse.leshan.core.californium.LwM2mCoapResource.handleRequest(LwM2mCoapResource.java:51)
        at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:106)
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:218)
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
        at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:562)
        at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:296)
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
        at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:140)
        at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:302)
        at org.eclipse.californium.core.network.UdpMatcher$2.run(UdpMatcher.java:289)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:290)
        at org.eclipse.californium.core.network.CoapEndpoint$6.run(CoapEndpoint.java:1341)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.UnknownFormatConversionException: Conversion = '%'
        at java.base/java.util.Formatter.checkText(Formatter.java:2732)
        at java.base/java.util.Formatter.parse(Formatter.java:2718)
        at java.base/java.util.Formatter.format(Formatter.java:2655)
        at java.base/java.util.Formatter.format(Formatter.java:2609)
        at java.base/java.lang.String.format(String.java:2897)
        at org.eclipse.leshan.core.link.lwm2m.attributes.LwM2mAttributeModel.getApplicabilityError(LwM2mAttributeModel.java:98)
        at org.eclipse.leshan.core.link.lwm2m.attributes.MixedLwM2mAttributeSet.validate(MixedLwM2mAttributeSet.java:97)
        at org.eclipse.leshan.core.link.lwm2m.DefaultLwM2mLinkParser.parseCoreLinkFormat(DefaultLwM2mLinkParser.java:149)
        ... 19 common frames omitted`

It seems that the "Object Version" attribute is attached to an object instance (e.g. /1/0) when it is only allowed for the object.
We know that this behavior is not fully consistent with the LwM2M standard but maybe we should allow such devices to register in the Leshan server ?

**Comment by sbernard31** [comment]
> It seems that the "Object Version" attribute is attached to an object instance (e.g. /1/0) when it is only allowed for the object.
We know that this behavior is not fully consistent with the LwM2M standard

Yep the LWM2M spec v1.1 and v1.0 are clear about that : 

See : 
 - http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#5-1-2-0-512-Attributes-Classification
 - http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf


> we should allow such devices to register in the Leshan server ?

This is a general question about how Leshan should handle device which doesn't strictly respect the specification. 

As I said at https://github.com/eclipse/leshan/issues/1270#issuecomment-1161799929
_"Why be strict by default, In a general way I try to explain this at (https://github.com/eclipse/leshan/issues/1103#issuecomment-937784837 (see answer to ""how should we do that ?"")

So the short idea, trying to be strict by default, but let user make their own server less strict if needed.
**I should really take time to create wiki page about this.** 

In your case you can create your own Parser : 
```java
// define your supported attributes 
Collection<AttributeModel<?>> supportedAttributes = new ArrayList<AttributeModel<?>>();
supportedAttributes.addAll(Attributes.ALL);
supportedAttributes.addAll(LwM2mAttributes.ALL);

// change the object_version one
supportedAttributes.remove(LwM2mAttributes.OBJECT_VERSION);
// create your custom model which support to assign OBJECT_VERSION To OBJECT and OBJECT_INSTANCE level instance.
supportedAttributes.add(new YourObjectVersionAttributeModel());

// add the new LinkParser
builder.setLinkParser(new DefaultLwM2mLinkParser(supportedAttributes));
```



> Caused by: java.util.UnknownFormatConversionException: Conversion = '%'

This is a bug you should get a message like : 
``` ver attribute is only applicable to [Object], and so can not be assigned to OBJECT_INSTANCE", getName(),

This is fixed in `master`.

**Comment by davidahoward** [comment]
I saw a similar problem:

https://github.com/eclipse/leshan/issues/1315

However, after carefully looking at the specification I closed my ticket.

It seems this is an area that will be made more clear in upcoming specifications.

For now, however, it would be helpful if leshan allowed the more compact format ...

There is discussion in the OMA DSME group that would codify the following behavior:

</44>;ver=2.2, </44/0>,</44/1> is OK.
</44>;ver=2.2 is OK (when there are instances of the Object 44).
</44/0>;ver=2.2 is OK.
But </44/0>;ver=2.2,</44/1>;ver=1.9 is not allowed.

**Comment by sbernard31** [comment]
I answer to that at : https://github.com/eclipse/leshan/issues/1315#issuecomment-1262387950

**Comment by JaroslawLegierski** [comment]
Yes it's a good idea. Thanks for explanation.
