### ISSUE TITLE
Help with running Leshan 1.4.x

### ISSUE THREAD

**Issue by minusdavid** [eclipse/leshan#1345]
I was hoping to use a stable version of Leshan for testing, so I downloaded Leshan 1.4.2 JARs with dependencies using this link: https://search.maven.org/search?q=g:org.eclipse.leshan%20AND%20v:1.4.2%20AND%20!a:leshan

I was trying to figure out what version of Java to use. According to https://github.com/eclipse/leshan/issues/924 it looks like Leshan 2.0.0 uses Java 8, but according to https://ci.eclipse.org/leshan/job/leshan-1.x/ it looks like Leshan 1.4.x uses Java 7...

It looks like Java 7 is pretty much completely EOL (with perhaps the exception of some commercial support from Azul).

That means it's challenging to find a binary distribution of Java 7 - at least on a newer OS.

**Comment by minusdavid** [comment]
I installed zulu7.56.0.11-ca-jdk7.0.352-linux_amd64.deb from https://www.azul.com/downloads/?version=java-7-lts&os=linux but got the following error from the Leshan server demo:

java -jar leshan-server-demo-1.4.2-jar-with-dependencies.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jetty/server/Handler : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:448)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:329)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
        at java.lang.Class.getMethod0(Class.java:2866)
        at java.lang.Class.getMethod(Class.java:1676)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:600)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:592)

**Comment by minusdavid** [comment]
Googling that error suggests that Leshan 1.4.2 was actually built with Java 8... so I'll give that a try next...

**Comment by minusdavid** [comment]
Installed OpenJDK 8 using "apt-get install openjdk-8-jdk" then ran "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar leshan-server-demo-1.4.2-jar-with-dependencies.jar" and it's working.

Next time I'll just use the "openjdk-8-jre-headless" package but that's good to know.

**Comment by jvermillard** [comment]
FYI I'm using Leshan 1.4 and 2.x with Java 17, I don't see any issues, usually JVM are pretty good at backward compatibility

**Comment by sbernard31** [comment]
I answer to most of your question at : https://github.com/eclipse/leshan/issues/924#issuecomment-1308489137

**Comment by minusdavid** [comment]
@jvermillard That's interesting! What JDK distribution are you using? 

@sbernard31 Much appreciated! :)
