### ISSUE TITLE
Connect Demo Client to Own Bootstrapserver with certificate usage CA constraint

### ISSUE THREAD

**Issue by Earthworn** [eclipse/leshan#1360]
### Question

Hi, 

I need some help connecting to my Bootstrapserver. 

I'm using Leshan Client Demo Version 2.0.0-M9 and wrote my own Leshan Bootstrapserver. I want to use X509 certificates with certificate usage CA constraint. My certificate structure is just a certificate authority above all certificates. The plan is, that the client and bootstrapserver only know the CA and their own certificate. 

I testet the code of the bootstrapserver with certificate usage 3 and it works fine. Here the server certificate is checked directly on client side. If i change it to certificate usage 0 and hand over the certifcate authority i get an error. For my understanding it should work like that. What am I missing? I'm also confused about the option -ts. Do i also need to place the certificate authority in the truststore? Shouldn't it be enough to just store it in -scert?

```java
    	LeshanBootstrapServerBuilder builder = new LeshanBootstrapServerBuilder();
    	
    	//Get Certificate for communication between Client and Bootstrapserver
    	PrivateKey BsServerprivateKey = null;
    	X509Certificate BsServerCertificate = null;
    	X509Certificate RootCertificate = null;
    	//Load Certificates
        try {
             BsServerprivateKey = SecurityUtil.privateKey.readFromFile("src\\main\\resources\\CA\\cprik_bs_server.der");
             BsServerCertificate = SecurityUtil.certificate.readFromFile("src\\main\\resources\\CA\\cert_bs_server.der");
             RootCertificate = SecurityUtil.certificate.readFromFile("src\\main\\resources\\CA\\root_cert.der");
         } catch (Exception e) {
             System.err.println("Unable to load Security files : " + e.getMessage());
             e.printStackTrace();
             return;
         }
    	
        //Set Certificates for Bootstrapserver builder
        builder.setPrivateKey(BsServerprivateKey);
        builder.setCertificateChain(new X509Certificate[] { BsServerCertificate, RootCertificate});        
        List<Certificate> trustStore = new ArrayList<>();
        trustStore.add((Certificate) RootCertificate);
        builder.setTrustedCertificates(trustStore.toArray(new Certificate[trustStore.size()]));
        
        //Set DLS Config for Bootstrapserver builder
        Configuration coapConfig = LeshanBootstrapServerBuilder.createDefaultCoapConfiguration();

        DtlsConnectorConfig.Builder dtlsConfig = new DtlsConnectorConfig.Builder(coapConfig);
        dtlsConfig.set(DtlsConfig.DTLS_RECOMMENDED_CIPHER_SUITES_ONLY, true);
        builder.setDtlsConfig(dtlsConfig);
        
    	//Build Bootstrapserver 
    	LeshanBootstrapServer bootstrapServer = builder.build();
    	// Start server
    	bootstrapServer.start();
 ```
 	
Log without -ts
```
java -jar leshan-client-demo_V_2.jar -b -n Levi -cu 0 -cprik Client_bs\\cprik_client_bs.der -ccert Client_bs\\cert_client_bs.der -scert CA_Certificates\\root_cert.der

                  LeshanClient 2022-11-24 12:49:50,775 [INFO] Starting Leshan client ...
                  LeshanClient 2022-11-24 12:49:50,779 [INFO] Leshan client[endpoint:Levi] started.
     DefaultRegistrationEngine 2022-11-24 12:49:50,780 [INFO] Trying to start bootstrap session to coaps://localhost:5684 ...
     DefaultRegistrationEngine 2022-11-24 12:49:50,785 [ERROR] Unexpected exception during bootstrap task
java.lang.IllegalArgumentException: The validated array is empty
        at org.eclipse.leshan.core.util.Validate.notEmpty(Validate.java:244)
        at org.eclipse.leshan.core.util.Validate.notEmpty(Validate.java:264)
        at org.eclipse.leshan.client.californium.CaConstraintCertificateVerifier.<init>(CaConstraintCertificateVerifier.java:67)
        at org.eclipse.leshan.client.californium.CaliforniumEndpointsManager.createEndpoint(CaliforniumEndpointsManager.java:189)
        at org.eclipse.leshan.client.engine.DefaultRegistrationEngine.clientInitiatedBootstrap(DefaultRegistrationEngine.java:220)
        at org.eclipse.leshan.client.engine.DefaultRegistrationEngine.access$200(DefaultRegistrationEngine.java:77)
        at org.eclipse.leshan.client.engine.DefaultRegistrationEngine$ClientInitiatedBootstrapTask.run(DefaultRegistrationEngine.java:527)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
                  LeshanClient 2022-11-24 12:49:50,785 [INFO] Destroying Leshan client ...
                  LeshanClient 2022-11-24 12:49:50,786 [INFO] Leshan client destroyed.
```
Log with -ts option 
```
java -jar leshan-client-demo_V_2.jar -b -n Levi -cu 0 -cprik Client_bs\\cprik_client_bs.der -ccert Client_bs\\cert_client_bs.der -scert root_cert.der -ts root_cert.der

                  LeshanClient 2022-11-24 12:54:47,087 [INFO] Starting Leshan client ...
                  LeshanClient 2022-11-24 12:54:47,091 [INFO] Leshan client[endpoint:Levi] started.
     DefaultRegistrationEngine 2022-11-24 12:54:47,091 [INFO] Trying to start bootstrap session to coaps://localhost:5684 ...
   CaliforniumEndpointsManager 2022-11-24 12:54:47,557 [INFO] New endpoint created for server coaps://localhost:5684 at coaps://0.0.0.0:64452
              LeshanClientDemo 2022-11-24 12:54:47,578 [INFO] DTLS Full Handshake initiated by client : STARTED ...
              LeshanClientDemo 2022-11-24 12:54:47,602 [INFO] DTLS Full Handshake initiated by client : FAILED (Certificate chain could not be validated - server identity does not match certificate)
     DefaultRegistrationEngine 2022-11-24 12:54:47,602 [INFO] Unable to send Bootstrap request : Certificate chain could not be validated - server identity does not match certificate
     DefaultRegistrationEngine 2022-11-24 12:54:47,603 [INFO] Try to initiated bootstarp in 600s..
```
I hope someone can clarify the issue.

**Comment by sbernard31** [comment]
(Do not hesitate to ask if this is not clear enough)

**Comment by sbernard31** [comment]
Here is the main reason why we decide to not support CA certificate as Trust Anchor for usage 0 : https://github.com/eclipse/leshan/issues/936

Tell me if you face an issue about this choice ? (E.g. you can not use usage 2)

**Comment by Earthworn** [comment]
Thanks for the quick response. 

I have no problem with using usage 2. I thought it would make no difference for my use case but thank you for the explaination.

Now, i tried to use usage 2. If i understood correct i will not need to define a Trust store here? Either way i still get the same error: 
 ```
Unable to send Bootstrap request : Certificate chain could not be validated - server identity does not match certificate
              LeshanClientDemo 2022-11-24 16:58:36,138 [INFO] DTLS Full Handshake initiated by client : FAILED (Certificate chain could not be validated - server identity does not match certificate)
 ```

**Comment by sbernard31** [comment]
Oops as you talk me about `-ts` option, I maybe missed the real issue :grimacing: 

`Certificate chain could not be validated - server identity does not match certificate` is raised by `BaseCertificateVerifier.validateSubject` : 
```java
protected void validateSubject(final InetSocketAddress peerSocket, final X509Certificate receivedServerCertificate)
        throws HandshakeException {

    if (X509CertUtil.matchSubjectDnsName(receivedServerCertificate, peerSocket.getHostName()))
        return;

    if (X509CertUtil.matchSubjectInetAddress(receivedServerCertificate, peerSocket.getAddress()))
        return;

    AlertMessage alert = new AlertMessage(AlertLevel.FATAL, AlertDescription.BAD_CERTIFICATE);
    throw new HandshakeException(
            "Certificate chain could not be validated - server identity does not match certificate", alert);
}
```

For all usage (except 3 as we directly trust the certificate) we check that IP/hostname of the server match the one in your certificate.

I guess this should not be the case for you.

**Comment by Earthworn** [comment]
Thank you this should be the problem
