### ISSUE TITLE
client or server seems to break after a certain amount of requests

### ISSUE THREAD

**Issue by Endebert** [eclipse/leshan#145]
Hi there,

We are currently doing performance tests with our application, which uses leshan as a base. We noticed that after a certain number of requests, the client or server seems to stop working.

In order for you to easily reproduce the behaviour, I did the same tests with leshan-server-demo and leshan-client-demo using the current master branch (0.1.11-M11-SNAPSHOT).

What I'm doing is very simple: Many GET requests on `http://localhost:8080/api/clients/liberator/6/0/1?format=TLV`. "liberator" is the name of my machine, and resource /6/0/1 was randomly chosen and is irrelevant to the problem (it's the longitude resource of the location instance).

Here is the log from the server:
```
Jun 14, 2016 2:52:02 PM org.eclipse.californium.core.network.config.NetworkConfig createStandardWithFile
INFO: Loading standard properties from file Californium.properties
Jun 14, 2016 2:52:03 PM org.eclipse.californium.core.CoapServer start
INFO: Starting server
Jun 14, 2016 2:52:03 PM org.eclipse.californium.core.network.CoapEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:5683
Jun 14, 2016 2:52:03 PM org.eclipse.californium.core.network.CoapEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:5684
Jun 14, 2016 2:52:03 PM org.eclipse.californium.scandium.DTLSConnector start
INFO: DTLS connector listening on [0.0.0.0/0.0.0.0:5684] with MTU [1,280] using (inbound) datagram buffer size [16,474 bytes]
[2016-06-14 14:52:03,159 INFO LeshanServer] LWM2M server started at coap://0.0.0.0/0.0.0.0:5683, coaps://0.0.0.0/0.0.0.0:5684.
[2016-06-14 14:52:03,320 INFO LeshanServerDemo] Web server started at http://10.147.65.152:8080/.
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49319, Token=8b66e8d00703d6, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49317, Token=9a, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49318, Token=4e615e119f, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49320, Token=a01cd274, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49321, Token=38f8db, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49322, Token=d86f8f, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49323, Token=b8d725, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49319, Token=8b66e8d00703d6, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49321, Token=38f8db, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49323, Token=b8d725, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49320, Token=a01cd274, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49322, Token=d86f8f, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49318, Token=4e615e119f, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveResponse
INFO: Ignoring unmatchable piggy-backed response from /127.0.0.1:57340: ACK-2.05   MID=49317, Token=9a, OptionSet={"Content-Format":"unknown/1542"}, c4 01 39 36 2e 30 
[2016-06-14 14:53:22,279 WARN ClientServlet] Request /api/clients/liberator/6/0/1 timed out.
[2016-06-14 14:53:22,279 WARN ClientServlet] Request /api/clients/liberator/6/0/1 timed out.
[2016-06-14 14:53:22,282 WARN ClientServlet] Request /api/clients/liberator/6/0/1 timed out.
[2016-06-14 14:53:22,284 WARN ClientServlet] Request /api/clients/liberator/6/0/1 timed out.
[2016-06-14 14:53:22,286 WARN ClientServlet] Request /api/clients/liberator/6/0/1 timed out.
[2016-06-14 14:53:22,289 WARN ClientServlet] Request /api/clients/liberator/6/0/1 timed out.
[2016-06-14 14:53:22,291 WARN ClientServlet] Request /api/clients/liberator/6/0/1 timed out.
```

And this is the client output:
```
Jun 14, 2016 2:52:16 PM org.eclipse.californium.core.network.config.NetworkConfig createStandardWithFile
INFO: Loading standard properties from file Californium.properties
[2016-06-14 14:52:16,919 INFO LeshanClientDemo] Press 'w','a','s','d' to change reported Location.
[2016-06-14 14:52:16,920 INFO LeshanClient] Starting Leshan client ...
Jun 14, 2016 2:52:16 PM org.eclipse.californium.core.CoapServer start
INFO: Starting server
Jun 14, 2016 2:52:16 PM org.eclipse.californium.core.network.CoapEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:0
Jun 14, 2016 2:52:16 PM org.eclipse.californium.scandium.DTLSConnector start
INFO: DTLS connector listening on [0.0.0.0/0.0.0.0:38733] with MTU [1,280] using (inbound) datagram buffer size [16,474 bytes]
Jun 14, 2016 2:52:16 PM org.eclipse.californium.core.network.CoapEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:0
[2016-06-14 14:52:16,931 INFO LeshanClient] Leshan client started.
[2016-06-14 14:52:16,945 INFO RegistrationEngine] Trying to register to coap://localhost:5683 ...
[2016-06-14 14:52:16,988 INFO RegistrationEngine] Next registration update in 27.0s...
[2016-06-14 14:52:16,989 INFO RegistrationEngine] Registered with location '/rd/8VTMJcBHpt'.
[2016-06-14 14:52:43,990 INFO RegistrationEngine] Trying to update registration to coap://localhost:5683 ...
[2016-06-14 14:52:43,996 INFO RegistrationEngine] Next registration update in 27.0s...
[2016-06-14 14:52:43,997 INFO RegistrationEngine] Registration update succeed.
[2016-06-14 14:52:46,706 INFO MyLocation] Read on Location Resource 1
[2016-06-14 14:52:46,706 INFO MyLocation] Read on Location Resource 1
[2016-06-14 14:52:46,706 INFO MyLocation] Read on Location Resource 1
[2016-06-14 14:52:46,707 INFO MyLocation] Read on Location Resource 1
...
[2016-06-14 14:53:17,276 INFO MyLocation] Read on Location Resource 1
[2016-06-14 14:53:17,276 INFO MyLocation] Read on Location Resource 1
[2016-06-14 14:53:17,277 INFO MyLocation] Read on Location Resource 1
[2016-06-14 14:53:17,277 INFO MyLocation] Read on Location Resource 1
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49317, Token=fe1a59, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49318, Token=fa, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49319, Token=1b1fe161, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49320, Token=714d971d053ddd, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49321, Token=f87e2ad40e423698, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49322, Token=1b46, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:17 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49323, Token=9ca326a2eeb917, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49319, Token=1b1fe161, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49321, Token=f87e2ad40e423698, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49323, Token=9ca326a2eeb917, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49320, Token=714d971d053ddd, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49322, Token=1b46, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49318, Token=fa, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
Jun 14, 2016 2:53:19 PM org.eclipse.californium.core.network.Matcher receiveRequest
INFO: Duplicate request: CON-GET    MID=49317, Token=fe1a59, OptionSet={"Uri-Path":["6","0","1"], "Accept":"unknown/1542"}, no payload
```

FYI the line `Read on Location Resource 1` occurs 65539 times.

There might be a problem with MIDs, but I'm not sure.

**Comment by Endebert** [comment]
I forgot the add the tool and command I'm using for testing: It's httperf, the command used is:
```
httperf --server=localhost --port=8080 --uri=/api/clients/liberator/6/0/1?format=TLV --num-conns=1 --rate=1 --num-calls=100000 --timeout=1
```
The numer 65536 is important, because 65536 = 2^16, so somewhere there a variable limiting the amount of requests possible. Maybe the is a modulo operation missing somewhere, so far I haven't found the source of the problem.

**Comment by sbernard31** [comment]
I tested it on my side and get the same results than you.
I tried to test with ab:
     ab -c 5 -n 100000 
"http://localhost:8081/api/clients/liberator/6/0/1?format=TLV"

I get some request timeout arround 65536 requests, then after some 
minutes the requests is accepted again. (I bet this time is CoAP 
EXCHANGE_LIFETIME)
So I suspect the "CoAP deduplicator" which is responsible to detect 
duplicate message based on MID (16 bytes).
see CoAP spec: https://tools.ietf.org/html/rfc7252#section-4.5

To validate this theory, I tried to run the test with deduplicator by 
changing the californium config (Californium.properties).
Setting DEDUPLICATOR=NO_DEDUPLICATOR.

With this config no more timeout. This confirms my supposition.
(This is clearly not recommended to remove deduplicator in production)

Simon

**Comment by Endebert** [comment]
@sbernard31 Thank you very much for your feedback. Since you seem to also be a part of the californium team, do you have a suggestion what I can do in this situation to keep the system stable? From what I can tell, there seems to be no way around implementing a custom deduplicator that "never" breaks.

**Comment by sbernard31** [comment]
The spec ([§2.1](https://tools.ietf.org/html/rfc7252#section-2.1)) say that :
_"The Message ID is compact; its 16-bit size enables up to about 250 messages per second from one  endpoint to another with default protocol parameters."_

I suppose this covers a lot of real use case especially at client side, If you want more than that maybe coapTCP will be more adapted(No message ID). But the spec is still in draft and I'm not sure there is (mature) implementation for now.

The spec said the protocol limitation is about 250 messages per second **from one  endpoint to another**. This looks is a protocol limitation. This also means thats you could send 500 messages per seconds to 2 different peer. 

If you look at the spec ([§4.4](https://tools.ietf.org/html/rfc7252#section-4.4)), there is several way to implement this. Californium choose the more simple one.
_"In the simplest case, a CoAP endpoint generates Message IDs by keeping a single Message ID      variable, which is changed each time a new Confirmable or Non-confirmable message is sent, regardless the destination address or port."_
So I suppose that Californium is limited to 250 messages per seconds no matter the number of peers. This is an implementation limitation and this will be probably an issue at server side for Leshan.

I made a quick test using httperf (--wlog), 1 leshan server and 2 leshan clients:

    httperf --server=localhost --port=8081 --wlog=y,urls.httperf --num-conns=1 --rate=1 --num-calls=100000 --timeout=1 
(see [how to create urls.httperf file](http://blog.stoeckl.de/post/5185203525/pain-with-httperf-and-the-wlog-option))
This fails at 65536 requests too. So it seems to confirm the limitation.

**Comment by sophokles73** [comment]
See https://github.com/eclipse/californium/issues/57 for additional discussion ...

**Comment by Endebert** [comment]
@sbernard31, @sophokles73 

Thank you very much for your help and responses. We are going to discuss this matter internally to figure out how to proceed.

I believe this issue here can be closed, since the observed behaviour is caused by Californium and a result of the requirements of our application, which seem to go beyond the intended purpose of coap.

**Comment by zmsoft** [comment]
@Endebert @sbernard31 @sophokles73 
Storing standard properties in file Californium.properties
Is this step necessary?
When I was running at Android studio, I found that this file could not be created.
Here is the log from logcat

05-05 15:11:31.280 D/mwqi: Loading OMA standard object models
05-05 15:11:31.397 D/mwqi: min.zhu objectId=0
05-05 15:11:31.398 D/mwqi: min.zhu objectId=1
05-05 15:11:31.398 D/mwqi: min.zhu objectId=3
05-05 15:11:31.398 D/mwqi: min.zhu objectId=5
05-05 15:11:31.398 D/mwqi: min.zhu objectId=6
05-05 15:11:31.400 D/mwqi: min.zhu leshanClientBuilder localAddress=/0.0.0.0:0
05-05 15:11:31.401 D/mwqi: min.zhu leshanClientBuilder localSecureAddress=/0.0.0.0:0
05-05 15:11:31.401 D/mwqi: min.zhu leshanClient endpoint=min.zhuand localAddress=/0.0.0.0:0and localSecureAddress=/0.0.0.0:0
05-05 15:11:31.401 D/mwqi: min.zhu leshanClient Create CoAP non secure endpoint localAddress=/0.0.0.0:0
05-05 15:11:31.404 I/NetworkConfig: Storing standard properties in file Californium.properties
05-05 15:11:31.407 W/NetworkConfig: Error while storing properties to /Californium.properties
   java.io.FileNotFoundException: Californium.properties: open failed: EROFS (Read-only file system)
             at libcore.io.IoBridge.open(IoBridge.java:456)
             at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
             at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
             at java.io.FileWriter.<init>(FileWriter.java:42)
             at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:218)
             at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:205)
             at org.eclipse.californium.core.network.config.NetworkConfig.createStandardWithFile(NetworkConfig.java:170)
            at org.eclipse.californium.core.network.config.NetworkConfig.getStandard(NetworkConfig.java:125)
            at org.eclipse.californium.core.network.CoapEndpoint.<init>(CoapEndpoint.java:166)
            at org.eclipse.leshan.client.californium.LeshanClient.<init>(LeshanClient.java:87)
            at org.eclipse.leshan.client.californium.LeshanClientBuilder.build(LeshanClientBuilder.java:120)

            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
            at libcore.io.Posix.open(Native Method)
            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
            at libcore.io.IoBridge.open(IoBridge.java:442)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
            at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
            at java.io.FileWriter.<init>(FileWriter.java:42) 
            at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:218) 
            at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:205) 
            at org.eclipse.californium.core.network.config.NetworkConfig.createStandardWithFile(NetworkConfig.java:170) 
            at org.eclipse.californium.core.network.config.NetworkConfig.getStandard(NetworkConfig.java:125) 
            at org.eclipse.californium.core.network.CoapEndpoint.<init>(CoapEndpoint.java:166) 
            at org.eclipse.leshan.client.californium.LeshanClient.<init>(LeshanClient.java:87) 
            at org.eclipse.leshan.client.californium.LeshanClientBuilder.build(LeshanClientBuilder.java:120) 

            at android.view.View.performClick(View.java:4780) 
            at android.view.View$PerformClick.run(View.java:19866) 
            at android.os.Handler.handleCallback(Handler.java:739) 
            at android.os.Handler.dispatchMessage(Handler.java:95) 
            at android.os.Looper.loop(Looper.java:135) 
            at android.app.ActivityThread.main(ActivityThread.java:5254) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at java.lang.reflect.Method.invoke(Method.java:372) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
05-05 15:11:31.447 D/mwqi: Starting Leshan client ...
05-05 15:11:31.448  I/CoapServer: Starting server
05-05 15:11:31.448  I/CoapEndpoint: Starting endpoint at /0.0.0.0:0
05-05 15:11:31.459  I/DTLSConnector: DTLS connector listening on [{0}] with MTU [{1}] using (inbound) datagram buffer size [{2} bytes]
05-05 15:11:31.464  I/CoapEndpoint: Starting endpoint at /0.0.0.0:0
05-05 15:11:31.475  D/mwqi: Leshan client started.


Although the client has started.But did not successfully connect to the server.
Connected clients: 0
Is it because this property file does not create the cause of success?

**Comment by sophokles73** [comment]
@zmsoft please use the mailing list for asking questions or create a new issue. Your inquiry doesn't seem related to this issue (which is BTW already closed), or is it?

**Comment by zmsoft** [comment]
@sophokles73 Thank you very much for your help and responses.
