### ISSUE TITLE
stacktrace when missing content format

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#164]
During tests, I faced some stacktraces:

```
java.lang.IllegalArgumentException: The validated object is null
	at org.eclipse.leshan.util.Validate.notNull(Validate.java:222)
	at org.eclipse.leshan.util.Validate.notNull(Validate.java:205)
	at org.eclipse.leshan.core.node.codec.DefaultLwM2mNodeDecoder.decodeTimestampedData(DefaultLwM2mNodeDecoder.java:79)
	at org.eclipse.leshan.server.californium.impl.CaliforniumObservationRegistryImpl.onNotification(CaliforniumObservationRegistryImpl.java:214)
	at org.eclipse.californium.core.network.CoapEndpoint$NotificationDispatcher.onNotification(CoapEndpoint.java:547)
	at org.eclipse.californium.core.network.Matcher$3.onResponse(Matcher.java:407)
	at org.eclipse.californium.core.coap.Request.setResponse(Request.java:416)
	at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverResponse(ServerMessageDeliverer.java:169)
	at org.eclipse.californium.core.network.stack.CoapStack$StackTopAdapter.receiveResponse(CoapStack.java:195)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveResponse(AbstractLayer.java:101)
	at org.eclipse.californium.core.network.stack.ObserveLayer.receiveResponse(ObserveLayer.java:146)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveResponse(AbstractLayer.java:101)
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveResponse(BlockwiseLayer.java:322)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveResponse(AbstractLayer.java:101)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveResponse(ReliabilityLayer.java:265)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveResponse(AbstractLayer.java:101)
	at org.eclipse.californium.core.network.stack.CoapStack.receiveResponse(CoapStack.java:138)
	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveMessage(CoapEndpoint.java:747)
	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.access$900(CoapEndpoint.java:647)
	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl$1.run(CoapEndpoint.java:661)
	at org.eclipse.californium.core.network.CoapEndpoint$5.run(CoapEndpoint.java:819)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

org.eclipse.leshan.server.californium.impl.CaliforniumObservationRegistryImpl.onNotification
```
                // get content format
                ContentFormat contentFormat = null;
                if (coapResponse.getOptions().hasContentFormat()) {
                    contentFormat = ContentFormat.fromCode(coapResponse.getOptions().getContentFormat());
                }

                // decode response
                List<TimestampedLwM2mNode> content = decoder.decodeTimestampedData(coapResponse.getPayload(),
                        contentFormat, observation.getPath(), model);
```
org.eclipse.leshan.core.node.codec.DefaultLwM2mNodeDecoder.decodeTimestampedData
```
        Validate.notNull(format);
```

So it will be `null`, if the content format option is not provided.
But shouldn't then the "new" default content foramt, TLV, be used?

**Comment by msangoi** [comment]
The content format is now mandatory in the response message. So there is no "default" format anymore.
But I agree that we could handle it in a better way than raising an exception :)
I'm not in favour of falling back to a default content format in the leshan implementation (in order to push the clients to implement the new behaviour).

**Comment by boaks** [comment]
OK! Mystic to me: why is the MUST only for response with payload and not also for request with payload.

**Comment by sbernard31** [comment]
>OK! Mystic to me: why is the MUST only for response with payload and not also for request with payload.
+1

**Comment by sophokles73** [comment]
@boaks 

> OK! Mystic to me: why is the MUST only for response with payload and not also for request with payload.

You should try to create a CR for the LWM2M TS :-)

**Comment by boaks** [comment]
Uups, my fault.

I already reported that to the OMA and get also an answer

https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/125

So, it's also a **MUST** for requests, but this is documented in an other section.
