### ISSUE TITLE
Problem with Redis PSUBSCRIBE for Cluster Registries

### ISSUE THREAD

**Issue by mhuelfen** [eclipse/leshan#173]
Hello I have a problem when using the classes from the leshan cluster project the server starts without any problem but after a while this error happens

```
2016-09-13 15:01:57.815  WARN 1666 --- [       Thread-5] o.e.l.s.d.cluster.RedisClientRegistry    : Redis PSUBSCRIBE interrupted.

java.lang.AbstractMethodError: redis.clients.jedis.JedisPubSub.onPSubscribe(Ljava/lang/String;I)V
	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:151)
	at redis.clients.jedis.JedisPubSub.proceedWithPatterns(JedisPubSub.java:96)
	at redis.clients.jedis.Jedis.psubscribe(Jedis.java:2826)
	at org.eclipse.leshan.server.demo.cluster.RedisClientRegistry$1.run(RedisClientRegistry.java:68)
	at java.lang.Thread.run(Thread.java:745)
```

Than this error is repeated in the log for about a minute and about 60 - 70 
```
2016-09-13 15:01:58.317  WARN 1666 --- [       Thread-5] o.e.l.s.d.cluster.RedisClientRegistry    : Relaunch Redis PSUBSCRIBE.
2016-09-13 15:01:58.318  WARN 1666 --- [       Thread-5] o.e.l.s.d.cluster.RedisClientRegistry    : Redis PSUBSCRIBE interrupted.


redis.clients.jedis.exceptions.JedisDataException: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
	at redis.clients.jedis.Protocol.processError(Protocol.java:113)
	at redis.clients.jedis.Protocol.process(Protocol.java:131)
	at redis.clients.jedis.Protocol.read(Protocol.java:200)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:285)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:184)
	at redis.clients.jedis.Jedis.configSet(Jedis.java:2797)
	at org.eclipse.leshan.server.demo.cluster.RedisClientRegistry$1.run(RedisClientRegistry.java:67)
	at java.lang.Thread.run(Thread.java:745)

```
In the end it stops and the relaunch seems to have ended 
```2016-09-13 15:01:58.317  WARN 1666 --- [       Thread-5] o.e.l.s.d.cluster.RedisClientRegistry    : Relaunch Redis PSUBSCRIBE.```

This is how I set up my Leshan Server

```
	@Bean
	public LeshanServer getLeshanServer(JedisPool jedisPool) {
		// Use those ENV variables for specifying the interface to be bound for
		// coap and coaps
		String iface = System.getenv("COAPIFACE");
		String ifaces = System.getenv("COAPSIFACE");

		// Build LWM2M server
		LeshanServerBuilder builder = new LeshanServerBuilder();
		if (iface != null && !iface.isEmpty()) {
			String[] add = iface.split(":");
			builder.setLocalAddress(add[0], Integer.parseInt(add[1]));
		}
		if (ifaces != null && !ifaces.isEmpty()) {
			String[] adds = ifaces.split(":");
			builder.setLocalSecureAddress(adds[0], Integer.parseInt(adds[1]));
		}

		RedisSecurityRegistry securityRegistry = new RedisSecurityRegistry(jedisPool, null, null);
		builder.setSecurityRegistry(securityRegistry);
		RedisClientRegistry clientRegistry = new RedisClientRegistry(jedisPool);
		builder.setClientRegistry(clientRegistry);
		LwM2mModelProvider objectModelProvider = new CustomModelProvider("objectspec.json");
		builder.setObjectModelProvider(objectModelProvider);
		builder.setEncoder(new DefaultLwM2mNodeEncoder());
		LwM2mNodeDecoder decoder = new DefaultLwM2mNodeDecoder();
		builder.setDecoder(decoder);
		builder.setObservationRegistry(
				new RedisObservationRegistry(jedisPool, clientRegistry, objectModelProvider, decoder));

		LeshanServer lwServer = builder.build();

		return lwServer;
	}
```

For the JedisPoolConfig I tried using the default settings and playing around with the min and max thread settings without any change.

Looking for a solution I only found this
http://stackoverflow.com/questions/12119471/redis-pub-sub-with-jedis-sub-crashes-with-error

**Comment by mhuelfen** [comment]
I found the solution the project also had an older jedis version
