### ISSUE TITLE
server cannot read null object link

### ISSUE THREAD

**Issue by pasear** [eclipse/leshan#200]
Hello there,
I am testing the object link feature and found this issue.

When a client sends an object link of MAX ID: MAX ID, that is, 65535:65535 to the server,
the server errs with
```
[2016-11-10 18:53:38,569 WARN ClientServlet] Invalid request or response
java.lang.IllegalArgumentException: The validated expression is false
        at org.eclipse.leshan.util.Validate.isTrue(Validate.java:182) ~[leshan-server-demo-0.1.11-M15-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.eclipse.leshan.core.node.ObjectLink.<init>(ObjectLink.java:46) ~[leshan-server-demo-0.1.11-M15-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.eclipse.leshan.tlv.TlvDecoder.decodeObjlnk(TlvDecoder.java:196) ~[leshan-server-demo-0.1.11-M15-SNAPSHOT-jar-with-dependencies.jar:?]
```

I doubt this is because TlvDecoder.decodeObjlnk() does not properly treat unsigned integer and converts 65535 into -1, which cannot pass the test at ObjectLink().
Hope that helps.
Thank you.

**Comment by sbernard31** [comment]
Fixed in master (see commit 8a4c9c7a63ebae24331c067c1c9e43b9220b36bc)
