### ISSUE TITLE
Could not send datagram error with multiple LWM Servers

### ISSUE THREAD

**Issue by mhuelfen** [eclipse/leshan#243]
I am getting "Could not send datagram" error with multiple LWM Servers with M14.

We have 2 LWM Servers running in Docker containers on different machines.

We use the standard lwm2m port for secure connections.

`Could not send datagram java.io.IOException: Operation not permitted at java.net.PlainDatagramSocketImpl.send(Native Method) at java.net.DatagramSocket.send(DatagramSocket.java:693) at org.eclipse.californium.scandium.DTLSConnector.sendDatagram(DTLSConnector.java:1341)
 at org.eclipse.californium.scandium.DTLSConnector.sendFlight(DTLSConnector.java:1322) at org.eclipse.californium.scandium.DTLSConnector.handleTimeout(DTLSConnector.java:1360) at org.eclipse.californium.scandium.DTLSConnector.access$600(DTLSConnector.java:112)
 at org.eclipse.californium.scandium.DTLSConnector$RetransmitTask.run(DTLSConnector.java:1494) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745) _`

**Comment by sbernard31** [comment]
I have doubt about this could be a Leshan issue.

Could you give us more details when this happen to try to understand.

Look at this issue maybe this could help you : https://github.com/AdguardTeam/AdguardForAndroid/issues/840#issuecomment-257817633

**Comment by sbernard31** [comment]
any update on this ?

**Comment by sbernard31** [comment]
I close this issue as this is surely not a Leshan issue. Feel free to reopen it, if you have more information about that.
