### ISSUE TITLE
Can not build using OpenJDK 9

### ISSUE THREAD

**Issue by mark-blackburn-etcorp** [eclipse/leshan#287]
I'm using a Ubuntu 16.04 x64 system

```
$ apt-get install maven openjdk-9-jdk # may be installed by default
$ git clone https://github.com/eclipse/leshan.git
$ cd leshan
$ mvn -X clean install
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 9-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-9-openjdk-amd64
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-31-generic", arch: "amd64", family: "unix"

[...]

[WARNING] Error injecting: org.codehaus.plexus.archiver.jar.JarArchiver
java.lang.ExceptionInInitializerError
        at org.codehaus.plexus.archiver.jar.JarArchiver$$FastClassByGuice$$180e749b.newInstance(<generated>)
[...]
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.<clinit>(AbstractZipArchiver.java:113)

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] leshan ............................................. FAILURE [  1.498 s]
[INFO] leshan - core ...................................... SKIPPED
```

I noticed that you are using Oracle's JDK 1.7 on Hudson. I couldn't figure out where to download that from and it's hard to get a version of OpenJDK 7 to install on current versions of Ubuntu. So I'm a bit stuck.

I tried installing OpenJDK 8 and point maven at that:

```
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
```

That at least got me this far:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] leshan ............................................. SUCCESS [ 11.778 s]
[INFO] leshan - core ...................................... SUCCESS [ 45.801 s]
[INFO] leshan - core californium .......................... SUCCESS [  3.439 s]
[INFO] leshan - server core ............................... SUCCESS [  5.289 s]
[INFO] leshan - server californium ........................ SUCCESS [  7.808 s]
[INFO] leshan - server cluster ............................ SUCCESS [ 24.148 s]
[INFO] leshan - client core ............................... SUCCESS [  6.886 s]
[INFO] leshan - client californium ........................ SUCCESS [  1.653 s]
[INFO] leshan - integration tests ......................... FAILURE [ 21.812 s]
[INFO] leshan - server demo ............................... SKIPPED
[INFO] leshan - client demo ............................... SKIPPED
[INFO] leshan - bootstrap server demo ..................... SKIPPED
```

**Comment by sbernard31** [comment]
About mvn + JDK 9, your response [here](https://stackoverflow.com/questions/36583118/is-maven-ready-for-jdk9).

  About JDK 8, it should work, but we face some instability with integration tests... Sometimes you need to relaunch it :(. If you have details about test failure, this could help to fix this instability.
