### ISSUE TITLE
Create Californium.properties file in Android,(NetworkConfig.getStandard())

### ISSUE THREAD

**Issue by zmsoft** [eclipse/leshan#338]
Storing standard properties in file Californium.properties
Is this step necessary?
When I was running at Android studio, I found that this file could not be created.
Here is the log from logcat

  05-05 15:11:31.280 D/mwqi: Loading OMA standard object models
  05-05 15:11:31.397 D/mwqi: min.zhu objectId=0
  05-05 15:11:31.398 D/mwqi: min.zhu objectId=1
  05-05 15:11:31.398 D/mwqi: min.zhu objectId=3
  05-05 15:11:31.398 D/mwqi: min.zhu objectId=5
  05-05 15:11:31.398 D/mwqi: min.zhu objectId=6
  05-05 15:11:31.400 D/mwqi: min.zhu leshanClientBuilder localAddress=/0.0.0.0:0
  05-05 15:11:31.401 D/mwqi: min.zhu leshanClientBuilder localSecureAddress=/0.0.0.0:0
  05-05 15:11:31.401 D/mwqi: min.zhu leshanClient endpoint=min.zhuand localAddress=/0.0.0.0:0and localSecureAddress=/0.0.0.0:0
  05-05 15:11:31.401 D/mwqi: min.zhu leshanClient Create CoAP non secure endpoint localAddress=/0.0.0.0:0
  05-05 15:11:31.404 I/NetworkConfig: Storing standard properties in file Californium.properties
  05-05 15:11:31.407 W/NetworkConfig: Error while storing properties to /Californium.properties
java.io.FileNotFoundException: Californium.properties: open failed: EROFS (Read-only file system)
  at libcore.io.IoBridge.open(IoBridge.java:456)
  at java.io.FileOutputStream.(FileOutputStream.java:87)
  at java.io.FileOutputStream.(FileOutputStream.java:72)
  at java.io.FileWriter.(FileWriter.java:42)
  at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:218)
  at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:205)
  at    org.eclipse.californium.core.network.config.NetworkConfig.createStandardWithFile(NetworkConfig.java:170)
  at org.eclipse.californium.core.network.config.NetworkConfig.getStandard(NetworkConfig.java:125)
  at org.eclipse.californium.core.network.CoapEndpoint.(CoapEndpoint.java:166)
  at org.eclipse.leshan.client.californium.LeshanClient.(LeshanClient.java:87)
  at org.eclipse.leshan.client.californium.LeshanClientBuilder.build(LeshanClientBuilder.java:120)

  at android.view.View.performClick(View.java:4780)
  at android.view.View$PerformClick.run(View.java:19866)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5254)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
  Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
  at libcore.io.Posix.open(Native Method)
  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
  at libcore.io.IoBridge.open(IoBridge.java:442)
  at java.io.FileOutputStream.(FileOutputStream.java:87) 
  at java.io.FileOutputStream.(FileOutputStream.java:72) 
  at java.io.FileWriter.(FileWriter.java:42) 
  at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:218) 
  at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:205) 
  at    org.eclipse.californium.core.network.config.NetworkConfig.createStandardWithFile(NetworkConfig.java:170) 
  at org.eclipse.californium.core.network.config.NetworkConfig.getStandard(NetworkConfig.java:125) 
  at org.eclipse.californium.core.network.CoapEndpoint.(CoapEndpoint.java:166) 
  at org.eclipse.leshan.client.californium.LeshanClient.(LeshanClient.java:87) 
  at org.eclipse.leshan.client.californium.LeshanClientBuilder.build(LeshanClientBuilder.java:120) 

  at android.view.View.performClick(View.java:4780) 
  at android.view.View$PerformClick.run(View.java:19866) 
  at android.os.Handler.handleCallback(Handler.java:739) 
  at android.os.Handler.dispatchMessage(Handler.java:95) 
  at android.os.Looper.loop(Looper.java:135) 
  at android.app.ActivityThread.main(ActivityThread.java:5254) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at java.lang.reflect.Method.invoke(Method.java:372) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
  05-05 15:11:31.447 D/mwqi: Starting Leshan client ...
  05-05 15:11:31.448 I/CoapServer: Starting server
  05-05 15:11:31.448 I/CoapEndpoint: Starting endpoint at /0.0.0.0:0
  05-05 15:11:31.459 I/DTLSConnector: DTLS connector listening on [{0}] with MTU [{1}] using     (inbound) datagram buffer size [{2} bytes]
  05-05 15:11:31.464 I/CoapEndpoint: Starting endpoint at /0.0.0.0:0
  05-05 15:11:31.475 D/mwqi: Leshan client started.

Although the client has started.But did not successfully connect to the server.
Connected clients: 0
Is it because this property file does not create the cause of success?
Is it possible to skip this step? I think it might be the reason that the client has not been successfully connected to the server.
 @sbernard31 @sophokles73

**Comment by boaks** [comment]
Use `NetworkConfig.createStandardWithoutFile()` at the begin of the main.

(but then you will stuck at loading the lwm2m data model :-) ). 

You may also consider my answer in the mailing list:

http://dev.eclipse.org/mhonarc/lists/leshan-dev/msg00813.html

**Comment by boaks** [comment]
Oh, currently I recognized, that the model is loaded from the classpath. So try to use `NetworkConfig.createStandardWithoutFile()` at the begin of the main.

**Comment by sbernard31** [comment]
Use `NetworkConfig.createStandardWithoutFile()` at the begin of the main is a good workaround for the `1.0.0-M1` version.
Now in master this file is not create anymore. (see #288)

Can we close this issue ?

**Comment by boaks** [comment]
@sbernard31 
This issue is for the LeshanClientDemo. I think, it still uses

> builder.setNetworkConfig(NetworkConfig.getStandard());

**Comment by sbernard31** [comment]
@boaks I can not see any reference to LeshanClientDemo on the stackstrace, so I supposed LeshanClientDemo was not used.

You're right for demo even in master we create a Californium.properties files. And you point the good line. Removing it avoid the file creation. (a default inmemory only config is created)
