### ISSUE TITLE
Leshan server extranet deployment

### ISSUE THREAD

**Issue by zmsoft** [eclipse/leshan#343]
When I deployed the Leshan server outside the network, I started the service, and then started the client, it couldn't work properly.

Here is the log

  五月 19, 2017 5:22:50 下午 org.eclipse.californium.core.network.config.NetworkConfig load
  信息: loading properties from file C:\Users\Administrator\Documents\GitHub\leshan\leshan-server-    demo\Californium.properties
  五月 19, 2017 5:22:52 下午 org.eclipse.californium.core.CoapServer start
  信息: Starting server
  五月 19, 2017 5:22:52 下午 org.eclipse.californium.core.network.CoapEndpoint start
  信息: Starting endpoint at coap://119.254.97.61:5683
  五月 19, 2017 5:22:52 下午 org.eclipse.californium.core.network.CoapEndpoint stop
  信息: Stopping endpoint at address coap://119.254.97.61:5683
  五月 19, 2017 5:22:52 下午 org.eclipse.californium.core.CoapServer start
  严重: Cannot start server endpoint [/119.254.97.61:5683]
  java.net.BindException: Cannot assign requested address: Cannot bind
	at java.net.DualStackPlainDatagramSocketImpl.socketBind(Native Method)
	at java.net.DualStackPlainDatagramSocketImpl.bind0(Unknown Source)
	at java.net.AbstractPlainDatagramSocketImpl.bind(Unknown Source)
	at java.net.DatagramSocket.bind(Unknown Source)
	at java.net.DatagramSocket.<init>(Unknown Source)
	at java.net.DatagramSocket.<init>(Unknown Source)
	at org.eclipse.californium.elements.UDPConnector.start(UDPConnector.java:130)
	at org.eclipse.californium.core.network.CoapEndpoint.start(CoapEndpoint.java:414)
	at org.eclipse.californium.core.CoapServer.start(CoapServer.java:212)
	at org.eclipse.leshan.server.californium.impl.LeshanServer.start(LeshanServer.java:232)
	at   org.eclipse.leshan.server.demo.LeshanServerDemo.createAndStartServer(LeshanServerDemo.java:341)
	at org.eclipse.leshan.server.demo.LeshanServerDemo.main(LeshanServerDemo.java:180)

  五月 19, 2017 5:22:52 下午 org.eclipse.californium.core.network.CoapEndpoint start
  信息: Starting endpoint at coaps://0.0.0.0:5684
  五月 19, 2017 5:22:52 下午 org.eclipse.californium.scandium.DTLSConnector start
  信息: DTLS connector listening on [0.0.0.0/0.0.0.0:5684] with MTU [1,280] using (inbound) datagram  buffer size [16,474 bytes]
  五月 19, 2017 5:22:52 下午 org.eclipse.californium.core.network.CoapEndpoint start
  信息: Started endpoint at coaps://0.0.0.0:5684
  2017-05-19 17:22:52,359 INFO LeshanServer - LWM2M server started at coap:///119.254.97.61:5683,   coaps://0.0.0.0/0.0.0.0:5684.
  2017-05-19 17:22:52,593 INFO LeshanServerDemo - Web server started at http://192.168.100.4:8080/.

**Comment by sbernard31** [comment]
I do not understand why the endpoint for 119.254.97.61:5683 is started then stopped, then started again ...
About BindException :
java.net.BindException: Cannot assign requested address: Cannot bind
at java.net.DualStackPlainDatagramSocketImpl.socketBind(Native Method)
at java.net.DualStackPlainDatagramSocketImpl.bind0(Unknown Source)

This generally happened when address is already in use.

I tested it on my side and it works.
