### ISSUE TITLE
Server without DTLS

### ISSUE THREAD

**Issue by bboeck** [eclipse/leshan#392]
Since M4 it is not possible to create a server without using dtls.

```java
public static void main (String args[]) {
    	LeshanServerBuilder builder = new LeshanServerBuilder();
        builder.disableSecuredEndpoint();
        LeshanServer server = builder.build();
        server.start();
    }
````

Even if disableSecuredEndpoint is set, I get the following exception
```
Exception in thread "main" java.lang.IllegalStateException: Supported cipher suites must be set either explicitly or implicitly by means of setting the identity or PSK store
	at org.eclipse.californium.scandium.config.DtlsConnectorConfig$Builder.build(DtlsConnectorConfig.java:872)
	at org.eclipse.leshan.server.californium.LeshanServerBuilder.build(LeshanServerBuilder.java:404)
```

**Comment by sbernard31** [comment]
Fixed in master (commit cd08129dd633d725943bd8e1c4b4d1b515e807d6)
