### ISSUE TITLE
Error Bootstraping lwM2M leshan client using json datamodel 

### ISSUE THREAD

**Issue by dherykw** [eclipse/leshan#446]
I am receiving this output when I try to init a default leshan device client through the demo bootstrap server reading the models from a obectspec.json (the previous version default one) file.  

        ClassLoader loader = LeshanClient.class.getClassLoader();
        URL url = loader.getResource("objectspec/objectspec.json");

        try {
            models = ObjectLoader.loadJsonStream(new FileInputStream(url.getFile()));
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

[RegistrationEngine#0] INFO org.eclipse.leshan.client.servers.RegistrationEngine - Trying to start bootstrap session to coap://leshan.eclipse.org:5783 ...
[RegistrationEngine#0] INFO org.eclipse.leshan.client.servers.RegistrationEngine - Bootstrap started
[CoapServer#1] ERROR org.eclipse.leshan.client.californium.impl.ObjectResource - Exception while handling request(CON-PUT    MID=34151, Token=b321fda44ce1c42c, OptionSet={"Uri-Path":["0","0"], "Content-Format":"application/vnd.oma.lwm2m+tlv"}, 
c8 00 1e 63 6f 61 70 3a 2f 2f 6c 65 73 68 61 6e 2e 65 63 6c 69 70 73 65 2e 6f 72 67 3a 35 37 38
33 c1 01 01 c1 02 03 c0 03 c0 04 c0 05 c1 06 03 c0 07 c0 08 c0 09 c1 0a 6f c1 0b 01 c1 0c 00 ) on the /0 resource
java.lang.NumberFormatException: Zero length BigInteger
at org.eclipse.leshan.tlv.TlvDecoder.decodeInteger(TlvDecoder.java:203)
	at org.eclipse.leshan.core.node.codec.tlv.LwM2mNodeTlvDecoder.parseTlvValue(LwM2mNodeTlvDecoder.java:201)
	at org.eclipse.leshan.core.node.codec.tlv.LwM2mNodeTlvDecoder.parseResourceTlv(LwM2mNodeTlvDecoder.java:170)
	at org.eclipse.leshan.core.node.codec.tlv.LwM2mNodeTlvDecoder.parseObjectInstanceTlv(LwM2mNodeTlvDecoder.java:154)
	at org.eclipse.leshan.core.node.codec.tlv.LwM2mNodeTlvDecoder.parseTlv(LwM2mNodeTlvDecoder.java:120)
	at org.eclipse.leshan.core.node.codec.tlv.LwM2mNodeTlvDecoder.decode(LwM2mNodeTlvDecoder.java:52)
	at org.eclipse.leshan.core.node.codec.DefaultLwM2mNodeDecoder.decode(DefaultLwM2mNodeDecoder.java:67)
	at org.eclipse.leshan.core.node.codec.DefaultLwM2mNodeDecoder.decode(DefaultLwM2mNodeDecoder.java:46)
	at org.eclipse.leshan.client.californium.impl.ObjectResource.handlePUT(ObjectResource.java:207)
	at org.eclipse.californium.core.CoapResource.handleRequest(CoapResource.java:217)
	at org.eclipse.leshan.client.californium.impl.ObjectResource.handleRequest(ObjectResource.java:97)
	at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:85)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:162)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:80)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:80)
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:311)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:222)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:80)
	at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:97)
	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveRequest(CoapEndpoint.java:837)
	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveMessage(CoapEndpoint.java:766)
	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.access$1000(CoapEndpoint.java:729)
	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl$1.run(CoapEndpoint.java:743)
	at org.eclipse.californium.core.network.CoapEndpoint$5.run(CoapEndpoint.java:981)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I have tried different versions of clients and servers, and reading the models from .xml files I have no problems.

Regards

**Comment by sbernard31** [comment]
I do not understand what you try to achieve with the code above ?

If you want to load and specific objectspec.json file.
You need to do that :
```java
try (InputStream stream = LeshanClient.class.getClassLoader().getResourceAsStream("objectspec/objectspec.json")) {
     models = ObjectLoader.loadJsonStream(stream);
} catch (IOException e) {
      e.printStackTrace();
}
```

By the way, json format is now deprecated, you should use official DDF(xml files) format from OMA instead.
More than that if you don't need to add custom model you just need to use : 
```java
ObjectLoader.loadDefault()
```
(which is generally automatically done by builder or initializer)

About your `java.lang.NumberFormatException: Zero length BigInteger`, 
If you want help you need to give us more information: 
Which version did you use exactly ?
I just test it now with master and it works for me.

I even succeed to decode your TLV payload : 
```java
byte[] bytes = Hex.decodeHex("c8001e636f61703a2f2f6c657368616e2e65636c697073652e6f72673a35373833c10101c10203c003c004c005c10603c007c008c009c10a6fc10b01c10c00".toCharArray());
Tlv[] tlvs = TlvDecoder.decode(ByteBuffer.wrap(bytes));
System.out.println(Arrays.toString(tlvs));
System.out.println(TlvDecoder.decodeString(tlvs[0].getValue()));
// output : 
// [Tlv [type=RESOURCE_VALUE, children=null, value=[99, 111, 97, 112, 58, 47, 47, 108, 101, 115, 104, 97, 110, 46, 101, 99, 108, 105, 112, 115, 101, 46, 111, 114, 103, 58, 53, 55, 56, 51], identifier=0], Tlv [type=RESOURCE_VALUE, children=null, value=[1], identifier=1], Tlv [type=RESOURCE_VALUE, children=null, value=[3], identifier=2], Tlv [type=RESOURCE_VALUE, children=null, value=[], identifier=3], Tlv [type=RESOURCE_VALUE, children=null, value=[], identifier=4], Tlv [type=RESOURCE_VALUE, children=null, value=[], identifier=5], Tlv [type=RESOURCE_VALUE, children=null, value=[3], identifier=6], Tlv [type=RESOURCE_VALUE, children=null, value=[], identifier=7], Tlv [type=RESOURCE_VALUE, children=null, value=[], identifier=8], Tlv [type=RESOURCE_VALUE, children=null, value=[], identifier=9], Tlv [type=RESOURCE_VALUE, children=null, value=[111], identifier=10], Tlv [type=RESOURCE_VALUE, children=null, value=[1], identifier=11], Tlv [type=RESOURCE_VALUE, children=null, value=[0], identifier=12]]
// coap://leshan.eclipse.org:5783
```

I suspect there is a problem with your model ...

**Comment by dherykw** [comment]
Hi sbernard31, nice to meet you

I am using a custom .json, I have tried with the default one just to be sure that my custom .json do not cause the error.

Yes, if you use it with ObjectLoader.loadDefault() it works like a charm, but loading a .json file fails...

I am checking in older version and i have the same error.

Thanks for advance,

**Comment by sbernard31** [comment]
Again I didn't advice your to use json format. Except if you have a really good reason to do so.
It seems there is an issue with your object 0 resource 0 description in your model. You should double-check it.

**Comment by dherykw** [comment]
The reason is that our current device management platform use the previous version of leshan, an it is not working properly with the devices that use the current version, so we have to do the connection with the previous version of leshan clients witch no accept the .xml schema. 

we are having problems with the current version of leshan clients in some others integration platforms like FIWARE LwM2M IoTAgents.

Those are the reason why I can't use .xml models.

I have use the default objectspec of the precious core leshan version just for be sure that the file is properly done.

**Comment by dherykw** [comment]
Just for helping other people with the same issue.

I have done a research and I have found the problem, OMA have changed the LWM2M Server SMS Number Object (/0/x/9) it was an integer but now is defined like a string, so if you use the json objectspec of previous versions you have to update it.
