### ISSUE TITLE
NullPointerException when get optional resource value 

### ISSUE THREAD

**Issue by arthur-xie** [eclipse/leshan#482]
I'm using leshan demo client to test our LwM2M server. In BOOTSTRAP INTERFACE, server put 2 security instances(one for bootstrap server, one for LwM2M server) and 1 server instance. To make the coap message as small as possible, there are some optional resources are omitted. As the OMA DDF definition:

```xml
      <Item ID="10">
	<Name>Short Server ID</Name>
        <Operations></Operations>
        <MultipleInstances>Single</MultipleInstances>
	<Mandatory>Optional</Mandatory>
	<Type>Integer</Type>
	<RangeEnumeration>1-65534</RangeEnumeration>
	<Units></Units>
	<Description><![CDATA[This identifier uniquely identifies each LwM2M Server configured for the LwM2M Client.
	This Resource MUST be set when the Bootstrap-Server Resource has false value.
	Specific ID:0 and ID:65535 values MUST NOT be used for identifying the LwM2M Server (Section 6.3 of the LwM2M version 1.0 specification).]]></Description>
      </Item>
```

The ```Short Server ID``` resource for security is optional when the instance is a bootstrap server(Bootstrap-Server Resource value is true). Unfortunately, that will make the leshan demo client raise a NullPointerException:

```
$ java -jar leshan-client-demo.jar -n DEVKIT -u localhost:5683 -b
2018-03-06 09:52:07,739 INFO LeshanClientDemo - Press 'w','a','s','d' to change reported Location (-53.0,10.0).
2018-03-06 09:52:07,741 INFO LeshanClient - Starting Leshan client ...
2018-03-06 09:52:07,762 INFO LeshanClient - Leshan client[endpoint:DEVKIT] started at coap://0.0.0.0/0.0.0.0:49170 coaps://0.0.0.0/0.0.0.0:49169
2018-03-06 09:52:07,773 INFO RegistrationEngine - Trying to start bootstrap session to coap://localhost:5683 ...
2018-03-06 09:52:07,807 INFO RegistrationEngine - Bootstrap started
2018-03-06 09:52:07,831 ERROR RegistrationEngine - Unexpected exception during update registration task
java.lang.NullPointerException
	at org.eclipse.leshan.client.servers.ServersInfoExtractor.getInfo(ServersInfoExtractor.java:60)
	at org.eclipse.leshan.client.servers.RegistrationEngine.bootstrap(RegistrationEngine.java:135)
	at org.eclipse.leshan.client.servers.RegistrationEngine.access$300(RegistrationEngine.java:54)
	at org.eclipse.leshan.client.servers.RegistrationEngine$RegistrationTask.run(RegistrationEngine.java:295)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The related code snippet:

```java
                if ((boolean) security.getResource(SEC_BOOTSTRAP).getValue()) { // Arthur comment: the current instance is a BOOTSTRAP SERVER
                    if (infos.bootstrap != null) {
                        LOG.warn("There is more than one bootstrap configuration in security object.");
                    } else {
                        // create bootstrap info
                        ServerInfo info = new ServerInfo();
                        info.serverId = (long) security.getResource(SEC_SERVER_ID).getValue(); // Arthur comment: for a BOOTSTRAP SERVER instance, the SERVER_ID is optional
                        info.serverUri = new URI((String) security.getResource(SEC_SERVER_URI).getValue());
                        info.secureMode = SecurityMode
                                .fromCode((long) security.getResource(SEC_SECURITY_MODE).getValue());
                        infos.bootstrap = info;
                    }
                } else {
                ...
```

**Comment by sbernard31** [comment]
You're right.
I made a PR to fix that #483.
Could you check if it behaves better ?
thx

**Comment by sbernard31** [comment]
Without any news about this I will integrate #483 in master tomorrow.

**Comment by sbernard31** [comment]
#483 is merged in master
