### ISSUE TITLE
Connecting Bootstrap issue

### ISSUE THREAD

**Issue by Venki7113** [eclipse/leshan#561]
Hi All, 

I am trying to connect leshan demo client to leshan bootstrap server with PSK, i am getting following error. Can you pls some one help me to resolve this? or what is the exact cmd line arguments i need to pass.
1) I added the New Client Bootstrap configuration in Web UI 
https://leshan.eclipse.org/bs/

Added 
Client enpoint  :xyz_123
LWM2M Server URL :coaps://leshan.eclipse.org:5684
Security mode :PSK
Id:Abcd_123
Scecret: Hex value of (String)

In Cmd line i started client
java -jar leshan-client-demo.jar -n xyz_123 -u leshan.eclipse.org:5784 -b -i asciivalueof(Abcd_123) -p Hex(String)

Getting following error:

2018-08-25 20:01:05,805 INFO LeshanClientDemo - Press 'w','a','s','d' to change reported Location (15.0,77.0).
2018-08-25 20:01:05,805 INFO LeshanClient - Starting Leshan client ...
2018-08-25 20:01:06,180 INFO LeshanClient - Leshan client[endpoint:VenClient] started at coap://0.0.0.0/0.0.0.0:58263 coaps://0.0.0.0/0.0.0.0:58262
2018-08-25 20:01:06,196 INFO RegistrationEngine - Trying to start bootstrap session to coaps://leshan.eclipse.org:5784 ...
2018-08-25 20:01:42,628 ERROR RegistrationEngine - Unexpected exception during update registration task
org.eclipse.leshan.core.request.exception.SendFailedException: Request CON-POST   MID= 2292, Token=[3485de401ca8685d], OptionSet={"Uri-Path":"bs", "Uri-Query":"ep=VenClient"}, no payload cannot be sent
        at org.eclipse.leshan.core.californium.CoapSyncRequestObserver.onSendError(CoapSyncRequestObserver.java:79)
        at org.eclipse.californium.core.coap.Message.setSendError(Message.java:755)
        at org.eclipse.californium.core.coap.Request.setSendError(Request.java:805)
        at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:1035)
        at org.eclipse.californium.elements.RawData.onError(RawData.java:256)
        at org.eclipse.californium.scandium.DTLSConnector$5.handshakeFailed(DTLSConnector.java:1394)
        at org.eclipse.californium.scandium.dtls.Handshaker.handshakeFailed(Handshaker.java:928)
        at org.eclipse.californium.scandium.DTLSConnector.handleTimeout(DTLSConnector.java:1534)
        at org.eclipse.californium.scandium.DTLSConnector.access$1200(DTLSConnector.java:152)
        at org.eclipse.californium.scandium.DTLSConnector$RetransmitTask$1.run(DTLSConnector.java:1679)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: handshake flight timeout!
        ... 6 more

**Comment by lianzeng** [comment]
i have the same issue when use -b -i  together,  it seems bootstrap process not support DTLS,   but when I just use -b option, the bs server not send the PSK to client,  i guess the demo client not implement Security Object Id(=0) ??  
btw: you can have a look at following page about DTLS https://developer.nordicsemi.com/nRF5_IoT_SDK/doc/0.9.0/html/a00082.html

**Comment by sbernard31** [comment]
@Venki7113, I think you made a mistake.

When you make a bootstrap, there is 2 kind of credentials : 
 - bootstrap server credentials
 - lwm2m server credentials

Let suppose you want to use psk to connect to bootstrap server.
You need to run your demo client with : 
```
java -jar leshan-client-demo.jar -n xyz_123 -u leshan.eclipse.org:5784 -b -i asciivalueof(Abcd_123) -p Hex(String)
```
At bootstrap server side (https://leshan.eclipse.org/bs/), you need to add this credentials using the new UI, you should add psk in **LWM2M bootstrap server** tab.

In a first time, you can just let No security for **LWM2M server** tab.

If this works (I just tested it on my side and this should works), you should see you device registered in https://leshan.eclipse.org/

The next step, is to use security for LWM2M server too. so you can delete the bootstrap config you just created and create a new one with same value for bootstrap server but now you set different credential in LWM2M server tab instead of using *no security*. (I advice you to first test with PSK, RPK is a bit more complex to set up). You should also add this credentials in LWM2M server https://leshan.eclipse.org/#/security.

And now you can restart, your client with exactly the same command line, the client will connect to bootstrap server, get the credential set for the LWM2M server and register to it.

**Comment by sbernard31** [comment]
I hope my previous answer helps without any feedback I close this issue.

**Comment by iliyas18** [comment]
Hey @sbernard31  the links you have provided is not accessing. I'm running the project in eclipse, so need some details to add new client to the bootstrap server

**Comment by sbernard31** [comment]
the sandbox URL changed now it's https://leshan.eclipseprojects.io.

(see https://github.com/eclipse/leshan/issues/648)
