### ISSUE TITLE
Public keys downloaded through web UI demo are not usable

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#575]
If you are using public key downloaded through web UI demo with leshan-client-demo, you will face : 

```
Unable to load RPK files : java.security.InvalidKeyException: invalid key format
java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: invalid key format
	at sun.security.ec.ECKeyFactory.engineGeneratePublic(ECKeyFactory.java:157)
	at java.security.KeyFactory.generatePublic(KeyFactory.java:334)
	at org.eclipse.leshan.util.SecurityUtil.extractPublicKey(SecurityUtil.java:59)
	at org.eclipse.leshan.util.SecurityUtil.extractPublicKey(SecurityUtil.java:49)
	at org.eclipse.leshan.client.demo.LeshanClientDemo.main(LeshanClientDemo.java:197)
Caused by: java.security.InvalidKeyException: invalid key format
	at sun.security.x509.X509Key.decode(X509Key.java:387)
	at sun.security.x509.X509Key.decode(X509Key.java:403)
	at sun.security.ec.ECPublicKeyImpl.<init>(ECPublicKeyImpl.java:69)
	at sun.security.ec.ECKeyFactory.implGeneratePublic(ECKeyFactory.java:219)
	at sun.security.ec.ECKeyFactory.engineGeneratePublic(ECKeyFactory.java:153)
	... 4 more
```

This is a bug in the javascript at web ui side which generate "bad" files.

Waiting the correct files for bsserver-demo and server-demo are available here : 
[serverPubKeys.zip](https://github.com/eclipse/leshan/files/2428160/serverPubKeys.zip)

**Comment by sbernard31** [comment]
Fixed by fbc01b8.
