### ISSUE TITLE
java.sql.Time is missing when running in a embedded JVM

### ISSUE THREAD

**Issue by msangoi** [eclipse/leshan#58]
I've tried to run to the Leshan client in a custom embedded JVM.
If the JVM was created with the 'compact1' profile (http://docs.oracle.com/javase/8/embedded/develop-apps-platforms/compact-profiles.htm), the java.sql.Time dependency is missing: 

```
Exception in thread "main" java.lang.NoClassDefFoundError: java/sql/Time
    at com.google.gson.Gson.<init>(Gson.java:230)
    at com.google.gson.GsonBuilder.create(GsonBuilder.java:545)
    at org.eclipse.leshan.core.model.ObjectLoader.<clinit>(ObjectLoader.java:46)
    at org.eclipse.leshan.client.resource.ObjectsInitializer.<init>(ObjectsInitializer.java:50)
    at org.eclipse.leshan.client.resource.ObjectsInitializer.<init>(ObjectsInitializer.java:45)
    at org.eclipse.leshan.client.example.LeshanClientExample.<init>(LeshanClientExample.java:82)
    at org.eclipse.leshan.client.example.LeshanClientExample.main(LeshanClientExample.java:68)
Caused by: java.lang.ClassNotFoundException: java.sql.Time
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 7 more
```

No problem when running in a 'compact2' JVM (adding JDBC package).
But it would be nice to be able to run the client in a minimal embedded JVM.

**Comment by sbernard31** [comment]
We remove the Gson dependency from leshan #383, so no more dependency to `java.sql.Time`.
