### ISSUE TITLE
leshan-client-demo couldn't register to leshan-bsserver-demo

### ISSUE THREAD

**Issue by aresbaker** [eclipse/leshan#658]
Dear expert,

I have downloaded leshan demo from github and run in my pc (Ubuntu 14.04).
But leshan-client-demo couldn't register to bootstrap server demo:
1. Run leshan bootstrap server demo :
```
java -jar ./leshan-bsserver-demo.jar
2019-02-26 14:23:40,581 INFO LeshanBootstrapServer - Bootstrap server started at coap://0.0.0.0/0.0.0.0:5683 coaps://0.0.0.0/0.0.0.0:5684
2019-02-26 14:23:40,713 INFO LeshanBootstrapServerDemo - Web server started at http://0.0.0.0:8080/.
```

2. Run leshan-client-demo in another command line:
```
java -jar leshan-client-demo.jar -b
2019-02-26 14:23:55,012 INFO LeshanClientDemo - Press 'w','a','s','d' to change reported Location (-73.0,80.0).
2019-02-26 14:23:55,013 INFO LeshanClient - Starting Leshan client ...
2019-02-26 14:23:55,018 INFO LeshanClient - Leshan client[endpoint:wangbin-OptiPlex-3020] started.
2019-02-26 14:23:55,018 INFO RegistrationEngine - Trying to start bootstrap session to coap://localhost:5683 ...
2019-02-26 14:23:55,051 INFO CaliforniumEndpointsManager - New endpoint created for server coap://127.0.0.1:5683 at coap://0.0.0.0:45639
2019-02-26 14:23:55,078 INFO RegistrationEngine - Bootstrap started
2019-02-26 14:23:55,102 INFO RegistrationEngine - Bootstrap finished Bootstrap Server [uri=coap://localhost:5683].
2019-02-26 14:23:55,104 INFO CaliforniumEndpointsManager - New endpoint created for server coap://0.0.0.0:5683 at coap://0.0.0.0:47376
2019-02-26 14:23:55,104 INFO RegistrationEngine - Trying to register to coap://0.0.0.0:5683 ...
2019-02-26 14:24:57,552 ERROR RegistrationEngine - Registration failed: Timeout.
2019-02-26 14:24:57,557 INFO CaliforniumEndpointsManager - Clear DTLS session for server coap://0.0.0.0:5683
2019-02-26 14:24:57,558 INFO RegistrationEngine - Trying to register to coap://0.0.0.0:5683 ...
2019-02-26 14:26:28,147 ERROR RegistrationEngine - Registration failed: Timeout.
```

Does bootstrap server need to be run with leshan-server-demo together?

Btw, when I run leshan-server-demo and leshan-client-demo, it could register normally.

Thanks & Regards

**Comment by sbernard31** [comment]
The bootstrap server is responsible to write some data on device.
In Leshan we call those data, bootstrap configuration.

This bootstrap configuration contains information needed by the device to register to a LWM2M server.

In your case the device successfully bootstrap : 
```
2019-02-26 14:23:55,078 INFO RegistrationEngine - Bootstrap started
2019-02-26 14:23:55,102 INFO RegistrationEngine - Bootstrap finished Bootstrap Server [uri=coap://localhost:5683].
```
Then it try to register itself on the new LWM2M server configured.
```
2019-02-26 14:23:55,104 INFO RegistrationEngine - Trying to register to coap://0.0.0.0:5683 ...
2019-02-26 14:24:57,552 ERROR RegistrationEngine - Registration failed: Timeout.
```
In your case the new LWM2M server address seems to be 0.0.0.0:5683...
I'm not sure 0.0.0.0 is a valid ip address but supposing it's ok and it refers to localhost...
It seems this is the same URI than bootstrap server ...
The bootstrap server is not LWM2M server and will just ignore the registration request (=> timeout !)

So you bootstrap configuration seems not correct !
I suspect all of this is not so clear, so I advice you to read the [LWM2M specification](http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf) at least **§5.2 Bootstrap Interface** and **§5.3 Client Registration Interface**

**Comment by aresbaker** [comment]
Dear sbernard31,

Thanks a lot for your response.

Do you mean bootstrap is responsible for configure the information of registration to LWM2M server ?
If we need to register to server in my case, I have to run leshan-bsserver-demo and leshan-server-demo with different port in the same time. Then leshan-client-demo could register to leshan-server-demo through leshan-bsserver-demo.

Is my understanding right?

Thanks & Regards

**Comment by sbernard31** [comment]
You're right.

**Comment by aresbaker** [comment]
Dear sbernard31,

Thanks a lot for your help!

It works for me.

BRs

**Comment by zq649** [comment]
Hi, I am facing the error while connecting to bootstrap server. I am newbie so need your help. please have a look at my logs

java -jar ./leshan-client-demo.jar -b

2019-09-27 19:39:56,930 INFO LeshanClientDemo - Press 'w','a','s','d' to change reported Location (-39.0,-40.0).
2019-09-27 19:39:56,931 INFO LeshanClient - Starting Leshan client ...
2019-09-27 19:39:56,936 INFO LeshanClient - Leshan client[endpoint:qasimOmen] started.
2019-09-27 19:39:56,937 INFO RegistrationEngine - Trying to start bootstrap session to coap://localhost:5683 ...
2019-09-27 19:39:56,974 INFO CaliforniumEndpointsManager - New endpoint created for server coap://localhost:5683 at coap://0.0.0.0:50744
2019-09-27 19:39:56,999 ERROR RegistrationEngine - Bootstrap failed: BAD_REQUEST no bootstrap config.
2019-09-27 19:39:56,999 INFO RegistrationEngine - Try to initiated bootstarp in 600s...

**Comment by sbernard31** [comment]
> Bootstrap failed: BAD_REQUEST no bootstrap config.

This means you didn't create a bootstrap config for you device.

**Comment by sbernard31** [comment]
maybe you can look at this : https://github.com/eclipse/leshan/issues/561

**Comment by zq649** [comment]
Could you please tell from where we can add config for the device?

**Comment by sbernard31** [comment]
see : https://github.com/eclipse/leshan#test-server-sandbox

**Comment by zq649** [comment]
Unable to access 
https://leshan.eclipseprojects.io/
https://leshan.eclipseprojects.io/bs/

**Comment by zq649** [comment]
Please have a look

Command: java -jar leshan-client-demo/target/leshan-clnt-demo-*-SNAPSHOT-jar-with-dependencies.jar -n mydev -u leshan.eclipseprojects.io:5784 -b -i 65666768 -p 707269766174655f6b6579

Output:
2019-09-28 15:06:30,770 INFO LeshanClientDemo - Press 'w','a','s','d' to change reported Location (-6.0,51.0).
2019-09-28 15:06:30,771 INFO LeshanClient - Starting Leshan client ...
2019-09-28 15:06:30,776 INFO LeshanClient - Leshan client[endpoint:mydev] started.
2019-09-28 15:06:30,776 INFO RegistrationEngine - Trying to start bootstrap session to coaps://leshan.eclipseprojects.io:5784 ...
2019-09-28 15:06:31,363 INFO CaliforniumEndpointsManager - New endpoint created for server coaps://leshan.eclipseprojects.io:5784 at coaps://0.0.0.0:35510
2019-09-28 15:07:03,083 WARN RegistrationEngine - Unable to send Bootstrap request : handshake flight 5 failed!

**Comment by sbernard31** [comment]
sandbox was done. I restarted apache this should be OK now.

If you have problem with the sandbox (e.g. it is down), you can just run server on your machine.
see https://github.com/eclipse/leshan#test-leshan-demos-locally

**Comment by zq649** [comment]
Hi, I am able to conncet to bootstrap server now. But unable to register. Can you guide me to solve it.
Bootstrap server command: 
java -jar leshan-bsserver-demo/target/leshan-server-demo-*-SNAPSHOT-jar-with-dependencies.jar --coaphost 192.168.10.4 --coapshost 192.168.10.4

Output:
2019-09-29 14:53:07,489 INFO LeshanBootstrapServer - Bootstrap server started at coap:///192.168.10.4:5683 coaps:///192.168.10.4:5684
2019-09-29 14:53:07,610 INFO LeshanBootstrapServerDemo - Web server started at http://0.0.0.0:8080/.

Server Command:
java -jar leshan-server-demo/target/leshan-server-demo-*-SNAPSHOT-jar-with-dependencies.jar 

Output:
2019-09-29 14:55:15,941 ERROR CoapServer - cannot start server endpoint [0.0.0.0/0.0.0.0:5683]
java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainDatagramSocketImpl.bind0(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93)


I have started bootstrap server at different address but it still gives me such error.

**Comment by zq649** [comment]
I have added the configuration on sandbox bootserver. My device bootstrap successfully but unable to register
![image](https://user-images.githubusercontent.com/37440553/65835139-fcf39000-e2fb-11e9-9ada-ebbf613dd2c3.png)

Started client by the command:
java -jar leshan-client-demo/target/leshan-client-demo-*-SNAPSHOT-jar-with-dependencies.jar -u leshan.eclipseprojects.io:5784 -n mydev -b -i 65666768 -p 707269766174655f6b6579

Output:
2019-09-29 20:56:48,476 INFO LeshanClientDemo - Press 'w','a','s','d' to change reported Location (80.0,-51.0).
2019-09-29 20:56:48,477 INFO LeshanClient - Starting Leshan client ...
2019-09-29 20:56:48,482 INFO LeshanClient - Leshan client[endpoint:mydev] started.
2019-09-29 20:56:48,483 INFO RegistrationEngine - Trying to start bootstrap session to coaps://leshan.eclipseprojects.io:5784 ...
2019-09-29 20:56:48,616 INFO CaliforniumEndpointsManager - New endpoint created for server coaps://leshan.eclipseprojects.io:5784 at coaps://0.0.0.0:50523
2019-09-29 20:56:49,851 INFO RegistrationEngine - Bootstrap started
2019-09-29 20:56:51,689 INFO RegistrationEngine - Bootstrap finished Bootstrap Server [uri=coaps://leshan.eclipseprojects.io:5784].
2019-09-29 20:56:51,698 INFO CaliforniumEndpointsManager - New endpoint created for server coaps://leshan.eclipseprojects.io:5684 at coaps://0.0.0.0:50184
2019-09-29 20:56:51,700 INFO RegistrationEngine - Trying to register to coaps://leshan.eclipseprojects.io:5684 ...
2019-09-29 20:58:03,738 ERROR RegistrationEngine - Registration failed: Timeout.
2019-09-29 20:58:03,739 INFO CaliforniumEndpointsManager - Clear DTLS session for server coaps://leshan.eclipseprojects.io:5684

I have also added security information on sandbox lwm2m server.
![image](https://user-images.githubusercontent.com/37440553/65835158-3c21e100-e2fc-11e9-86b0-da2cf26694d7.png)

**Comment by sbernard31** [comment]
@zq649, I succeed to reproduce your issue several time and so began to investigate what could happen on the sandbox. I didn't see anything strange in log or using jstak... while I was searching, (doing anything special at sandbox side) I finally see my client succeeding to connect to the sandbox.

Could you confirm it works for you now ?

What happened is really strange and I would really understand this, so please if you face this again let me know that quickly :pray: (Maybe I can go on the sandbox, try to investigate again)
