### ISSUE TITLE
Server-demo raises exceptions after serveral "read" operation on web client

### ISSUE THREAD

**Issue by richzzp** [eclipse/leshan#734]
We have tried leshan code both on latest version and the version after commit: 43c316758c194b9abeb0981e71fc0dbee406870c(Clean CoAP root resources, Tue Aug 20 18:07:57).
After serveral "read" operations through leshan web client, the server will raise exceptions with great probability:
```
org.eclipse.jetty.io.EofException
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:189)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:335)
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:125)
        at org.eclipse.jetty.server.HttpConnection$ContentCallback.process(HttpConnection.java:671)
        at org.eclipse.jetty.util.IteratingCallback.processIterations(IteratingCallback.java:166)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:126)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:303)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:719)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:752)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:135)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:128)
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:226)
        at org.eclipse.jetty.server.Response.flushBuffer(Response.java:1209)
        at org.eclipse.leshan.server.demo.utils.EventSourceServlet$EventSourceEmitter.flush(EventSourceServlet.java:208)
        at org.eclipse.leshan.server.demo.utils.EventSourceServlet$EventSourceEmitter.data(EventSourceServlet.java:171)
        at org.eclipse.leshan.server.demo.utils.EventSourceServlet$EventSourceEmitter.event(EventSourceServlet.java:156)
        at org.eclipse.leshan.server.demo.servlet.EventServlet$LeshanEventSource.sentEvent(EventServlet.java:243)
        at org.eclipse.leshan.server.demo.servlet.EventServlet.sendEvent(EventServlet.java:180)
        at org.eclipse.leshan.server.demo.servlet.EventServlet.access$100(EventServlet.java:49)
        at org.eclipse.leshan.server.demo.servlet.EventServlet$ClientCoapListener.trace(EventServlet.java:196)
        at org.eclipse.leshan.server.demo.servlet.log.CoapMessageTracer.receiveResponse(CoapMessageTracer.java:95)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveResponse(CoapEndpoint.java:908)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveMessage(CoapEndpoint.java:836)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.access$1000(CoapEndpoint.java:794)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl$1.run(CoapEndpoint.java:811)
        at org.eclipse.californium.core.network.CoapEndpoint$7.run(CoapEndpoint.java:1040)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Broken pipe
        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:167)
        ... 28 more
```

**Comment by richzzp** [comment]
root@u1804:/home/drvd/linux/leshan_orig# git branch -vv
* master f4df14bd [origin/master] Integration of Californium 2.0.0-M17
root@u1804:/home/drvd/linux/leshan_orig# git log
commit f4df14bdd82d5ee07f7ce01bdfb167511218a956 (HEAD -> master, origin/master, origin/HEAD)
Author: Simon Bernard <sbernard@sierrawireless.com>
Date:   Thu Sep 5 14:28:29 2019 +0200

    Integration of Californium 2.0.0-M17

**Comment by sbernard31** [comment]
Thx for reporting this.

The exception is raise in `leshan-server-demo` on [server-sent event](https://www.w3.org/TR/eventsource/) API. This API is just used by demo so not really intended to be reused.

I already see this kind of exception and if I understand it well this happened when the foreign peer (in our case, a http client like an internet browser) close the connection when we try to write on it.
see : https://stackoverflow.com/questions/15785175/java-io-ioexception-broken-pipe#15785439

> After serveral "read" operations through leshan web client, the server will raise exceptions with great probability ?

is it a new issue ? I mean do you feel this happened more often than before ?
is there more annoying behavior than just the log ?

**Comment by richzzp** [comment]
Hi, thanks for your kindly reply.
I've seen the same issues araised on some other places using Jetty engine,   since the API is just used as demo, and the subsequent operations worked well, it definitely didn't compact our development using leshan code. 
Thanks again to provide us this wonderful "software".

**Comment by sbernard31** [comment]
I keep this issue open, maybe we can handle this in a better way, but this will probably not be our priority list.
