### ISSUE TITLE
EndPoint Exception

### ISSUE THREAD

**Issue by Rahul365** [eclipse/leshan#735]
When i try to start the leshan server, got this exception after updating all library files.
Exception in thread "main" java.lang.AbstractMethodError: org.eclipse.leshan.server.californium.impl.InMemoryRegistrationStore.setExecutor(Ljava/util/concurrent/ScheduledExecutorService;)V
	at org.eclipse.californium.core.network.CoapEndpoint.setExecutors(CoapEndpoint.java:482)
	at org.eclipse.californium.core.CoapServer.setExecutors(CoapServer.java:212)
	at org.eclipse.californium.core.CoapServer.start(CoapServer.java:233)
	at org.eclipse.leshan.server.californium.impl.LeshanServer.start(LeshanServer.java:238)
	at com.jio.lwmserver.LWM2MServer.startServer(LWM2MServer.java:163)

**Comment by sbernard31** [comment]
I feel that the is a compilation issue. Did you try to recompile all ? 
(if you are using maven : `mvn clean install`, if you are using eclipse `Project/clean ...` menu)

**Comment by Rahul365** [comment]
> I feel that the is a compilation issue. Did you try to recompile all ?
> (if you are using maven : `mvn clean install`, if you are using eclipse `Project/clean ...` menu)

I just clean the project and started it again but still getting the same error.

**Comment by Rahul365** [comment]
is it because i am using different version of libraries like M12,M11,M10 ?

**Comment by sbernard31** [comment]
> is it because i am using different version of libraries like M12,M11,M10 ?

Yep probably. You should not to that :)

**Comment by Rahul365** [comment]
> > is it because i am using different version of libraries like M12,M11,M10 ?
> 
> Yep probably. You should not to that :)

Can you suggest which library versions i should stick with for now? So that i don't get such errors.

**Comment by sbernard31** [comment]
I would recommend you to use the last one :)

But if you are using any of them alone (without mixing), all should works !

Did you have any constraints about the californium version to use ?

**Comment by Rahul365** [comment]
I am using californium-core-2.0.0-M17.jar and same version of scandium.

**Comment by sbernard31** [comment]
Currently there is no leshan release which supports officially this californium version.
I just integrated it in `master` branch.

If I remember well, I didn't find any API break so this should works with leshan M12. If it doesn't, just use  (leshan-master + cf-2.0.0-M17) or (leshan-1.0.0M12 + cf-2.0.0-M16)
