### ISSUE TITLE
Leshan client Simulator

### ISSUE THREAD

**Issue by venky186** [eclipse/leshan#778]
Hi,
I was able to build leshan client code in eclipse and tried to connect server connected successfully. Thanks for the Leshan code.

My Question: 1) I need to create multiple (1000) Leshan clients from the same simulator and update sensor data based on a request by the simulator.

when I create those many clients, my pc was hanging . is there any proper way to handle these clients.

My Leshan server is a secure one.
Thanks,
Venkatesh

**Comment by sbernard31** [comment]
It's not clear to me, what means : _"my pc was hanging"_. :thinking: 

Anyway, Leshan client is not really optimized to do that, but this is something where we would like to be better.

Here is an issue about the Thread usage of Leshan client : https://github.com/eclipse/leshan/issues/491. I plan to work a bit more on that in the next month.

By the past, I also implemented [this](https://github.com/sbernard31/benchmark-clients) to be able to launch several Leshan clients in a row. (This is not up to date but maybe this could inspire yourself)
When I used it and if I remembered well, I was able to launch 1000/2000 clients  on my computer, but of course it depends on your configuration.

**Comment by venky186** [comment]
Thank you for the example given, I will check

**Comment by venky186** [comment]
hi, I am facing an error when I am trying to connect secure server, please help

**Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/californium/elements/util/Bytes
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.californium.scandium.dtls.pskstore.StaticPskStore.<init>(StaticPskStore.java:46)
	at org.eclipse.leshan.client.californium.impl.CaliforniumEndpointsManager.createEndpoint(CaliforniumEndpointsManager.java:90)
	at org.eclipse.leshan.client.californium.impl.CaliforniumEndpointsManager.createEndpoints(CaliforniumEndpointsManager.java:187)
	at org.eclipse.leshan.client.servers.RegistrationEngine.factoryBootstrap(RegistrationEngine.java:134)
	at org.eclipse.leshan.client.servers.RegistrationEngine.start(RegistrationEngine.java:116)
	at org.eclipse.leshan.client.californium.LeshanClient.start(LeshanClient.java:121)
	at org.eclipse.leshan.benchmark.client.BenchTestLeshanClient.start(BenchTestLeshanClient.java:278)
	at org.eclipse.leshan.benchmark.client.ClientsLauncher.start(ClientsLauncher.java:72)
	at org.eclipse.leshan.benchmark.client.ClientBenchTest.main(ClientBenchTest.java:25)
Caused by: java.lang.ClassNotFoundException: org.eclipse.californium.elements.util.Bytes
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)**

**Comment by venky186** [comment]
Thank you, Simon, for your quick response, 4000 clients are working :)

**Comment by venky186** [comment]
Hi Simon,

always **"exchange.getRelation()"** in coapResource.java class was giving Null.

 where do we need to configure the ObserveRelation?
from client or server-side?
if client-side how can I configure?

Thanks,
venkatesh.

**Comment by sbernard31** [comment]
Hi @venky186 ,

1. This seems to not be correlated with the current issue :thinking:. Am I right ?  
2. This is rather a californium question than the Leshan one.

Anyway, AFAIK, the ObserveRelation is only used by a CoAP server when handling a observe request. At LWM2M level for observe request the CoAP server is the LWM2M client.  So this ObserveRelation is only set by the CoAP Server (LWM2M client) when an observe relation is established. This is done by Californium and is not intended to be modified by end-user.

**Comment by venky186** [comment]
Thank you for clarification, do you have any sample code ?

**Comment by sbernard31** [comment]
Sample of code to do what ? :grin:

**Comment by venky186** [comment]
To set observed relation from CoAP Server (LWM2M client)

**Comment by sbernard31** [comment]
The relation is set/create when the CoAP Server(LWM2M client) receive a ObserveRequest from the CoAP client (LWM2M server), so just send it.

**Comment by venky186** [comment]
ya got it thanks:)

**Comment by sbernard31** [comment]
I suppose we can close it now
