### ISSUE TITLE
How to create Model - Cannot set Instances Class for Object 150 because no model is defined for this id

### ISSUE THREAD

**Issue by maridikirankumar** [eclipse/leshan#82]
Hi Team,

I am trying to learn leshan, started implementing custom object on the client side and ended up with following error.
I am no expert in Java, may be its basic question. but can any one help me how to and where to create the model.

I tried going through the code to see if there is any example object, but i could not find. If some one can point me to the class then i can try to learn from it. 

thanks much your help is much appreciated.

`Exception in thread "main" java.lang.IllegalArgumentException: Cannot set Instances Class for Object 150 because no model is defined for this id.
	at org.eclipse.leshan.client.resource.ObjectsInitializer.setInstancesForObject(ObjectsInitializer.java:79)
	at org.eclipse.leshan.client.demo.LeshanClientDemo.createAndStartClient(LeshanClientDemo.java:264)
	at org.eclipse.leshan.client.demo.LeshanClientDemo.main(LeshanClientDemo.java:200)`

**Comment by maridikirankumar** [comment]
never mind got it.
