### ISSUE TITLE
problem with load balancer observe/write requests

### ISSUE THREAD

**Issue by UnforgivenD** [eclipse/leshan#884]
Hi, 

Our project is trying to use cluster of leshan servers with load balancer.
We are using dtls and secure connections.
Without balancer everything working fine, but with load balancer we have a lot of

```
2020-09-01 15:09:07.680 DEBUG 8656 --- [/0.0.0.0:5684#5] o.e.c.scandium.dtls.Connection           : Handshake with [/172.19.1.157:56732] has failed
2020-09-01 15:09:07.680 DEBUG 8656 --- [/0.0.0.0:5684#5] o.e.californium.scandium.DTLSConnector   : Handshake with [/172.19.1.157:56732] failed, report error to deferred 1 messages
2020-09-01 15:09:07.680  WARN 8656 --- [/0.0.0.0:5684#5] s.a.l.c.MessageSenderErrorCallback       : onError of message send callback

org.eclipse.leshan.core.request.exception.SendFailedException: Unable to send request coap://172.19.1.157:56732/3/0/15
        at org.eclipse.leshan.core.californium.CoapAsyncRequestObserver.onSendError(CoapAsyncRequestObserver.java:167) [leshan-core-cf-1.1.0.jar!/:na]
        at org.eclipse.californium.core.coap.Message.setSendError(Message.java:1063) [californium-core-2.3.0.jar!/:na]
        at org.eclipse.californium.core.coap.Request.setSendError(Request.java:1131) [californium-core-2.3.0.jar!/:na]
        at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:1456) [californium-core-2.3.0.jar!/:na]
        at org.eclipse.californium.elements.RawData.onError(RawData.java:303) [element-connector-2.3.0.jar!/:na]
        at org.eclipse.californium.scandium.DTLSConnector$2.handshakeFailed(DTLSConnector.java:451) [scandium-2.3.0.jar!/:na]
        at org.eclipse.californium.scandium.dtls.Handshaker.handshakeFailed(Handshaker.java:1425) [scandium-2.3.0.jar!/:na]
        at org.eclipse.californium.scandium.DTLSConnector.processAlertRecord(DTLSConnector.java:1595) [scandium-2.3.0.jar!/:na]
        at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1330) [scandium-2.3.0.jar!/:na]
        at org.eclipse.californium.scandium.DTLSConnector$12.run(DTLSConnector.java:1195) [scandium-2.3.0.jar!/:na]
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276) [element-connector-2.3.0.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]
Caused by: org.eclipse.californium.scandium.dtls.HandshakeException: Received 'fatal alert'
        at org.eclipse.californium.scandium.DTLSConnector.processAlertRecord(DTLSConnector.java:1580) [scandium-2.3.0.jar!/:na]
        ... 6 common frames omitted
```

I've tried sending sync/async requests - seems it doesn't change anything.
Leshan version 1.1.0.
Could you please help with possible solutions?

please let me know if more details needed.

**Comment by sbernard31** [comment]
If you are interesting about using Leshan in cluster you should read [that](https://github.com/eclipse/leshan/wiki/Using-Leshan-server-in-a-cluster) (maybe it's already done :slightly_smiling_face:)

Now for your problem, it's not so easy to know :thinking: 
It seems you try to send a request. This request tries to initiate an handshake and the handshake fails.

So first question is it expected that your server initiate dtls handshake (and so behave like a dtls client) ? 
It could make sense (see [dtls_role_exchange](https://github.com/sbernard31/dtls-server#dtls-role-exchange)) but you need a client which support that.

Are you using only queue_mode for your device ? Are your devices behind a NAT ?

**Comment by UnforgivenD** [comment]
thanks for quick response.
I've tried to downgrade version to 1.0.0 and seems observe request/responses works now.

but there is another issue with notifications, it seems that after successful observe response it removing device from observations store

2020-09-02 16:06:59.423  INFO 7802 --- [pServer(main)#2] s.a.l.callback.MessageObserveCallback    : Observe-Ack = e6d41e67_efab_101;/3/0/15;1599062819423;/172.19.1.157
2020-09-02 16:06:59.424 DEBUG 7802 --- [pServer(main)#2] o.e.c.core.network.BaseMatcher           : observation with token Token=61E89B19B811EA4D not established, removing from observation store

and because of that I'm not receiving any notifications on changed resources. 
Maybe you have some thoughts ? 


client supports dtls role exchange and seems that he is sending observe notification to client.
I'm using not only queue mode, and devices is not behind NAT yet.


thanks in advance.

**Comment by sbernard31** [comment]
> I've tried to downgrade version to 1.0.0 and seems observe request/responses works now.

Meaning that you maybe find a bug in Leshan 1.1 ?

I bet this is because you response does not contains an observe option.

**Comment by UnforgivenD** [comment]
> Meaning that you maybe find a bug in Leshan 1.1 ?
It can be, I will report it if will have prove.

> I bet this is because you response does not contains an observe option.

could you please point to which field I should look for this option?
do you mean ObserveResponse->coapResponse->options object? 

with leshan client it contains {"Observe":7263, "Content-Format":"application/vnd.oma.lwm2m+json"} and it works fine, but with Waakama test client it doesn't work, so it could be client configuration?

**Comment by sbernard31** [comment]
> do you mean ObserveResponse->coapResponse->options object?

If you do an observe request, the client will answer as you make a read request except that if the response containt the observe option that means OK the observe relationship is established else it means I do not want/can not establish the relation.

**Comment by UnforgivenD** [comment]
thanks for help, it seems there was problem with observe request itself, client responding with error, but for some reasons it goes to successful callback.

**Comment by sbernard31** [comment]
You mean ResponseCallback from LeshanServer.send ?

If yes, ResponseCallback is called when response from device is received (success or error response).
ErrorCallback is if something wrong happened. (e.g. unable to decode payload, unable to send resquest, ... )

**Comment by UnforgivenD** [comment]
> You mean ResponseCallback from LeshanServer.send ?
yes, this callback, thanks for explanation.

other a little bit not related question - if I'm using RedisRegistrationStore in servers, and one is failed, device connected to this server still will be able to communicate with new server, chosen by load balancer?

**Comment by sbernard31** [comment]
I'm not sure to really get your question, but the answer should be in : https://github.com/eclipse/leshan/wiki/Using-Leshan-server-in-a-cluster#shared-stores

If not, please try to reformulate your question.
