### ISSUE TITLE
automatic writing to devices in leshan

### ISSUE THREAD

**Issue by UnforgivenD** [eclipse/leshan#942]
Hi, we are trying to run automatic writing test, so server will perform automatic writing to devices each 10 minutes.
for 75% of devices everything going fine, but for 25% after server trying to write to client, it got 552 error from client and removing that connection. 

server log:
```
32 38 30 66 64 31 35 3b 38 66 64 32 65 63 66 62 2d 36 36 39 36 2d 34 37 65 30 2d 38 65 35 35 2d
32 65 32 62 62 63 31 65 35 63 37 64 3b 33 33 39 38 64 33 65 64 2d 33 32 66 32 2d 34 64 31 39 2d
39 37 31 38 2d 31 63 66 35 31 62 39 65 64 39 31 31 3b 65 65 62 30 36 38 30 65 2d 30 38 61 33 2d
 .. 836 bytes
2020-12-01T15:31:06.759+0000 TRACE Processing FATAL ALERT from [/172.20.2.200:33735]: HANDSHAKE_FAILURE
2020-12-01T15:31:06.759+0000 DEBUG connection: missing connection for /172.20.6.91:33735!
2020-12-01T15:31:06.759+0000 TRACE create new connection for /172.20.6.91:33735
2020-12-01T15:31:06.759+0000 TRACE connection: add dtls-con: CID=14D696E231BF, /172.20.6.91:33735, is alive (size 849)

java.lang.Throwable: connection added!
        at org.eclipse.californium.scandium.dtls.InMemoryConnectionStore.put(InMemoryConnectionStore.java:311)
        at org.eclipse.californium.scandium.DTLSConnector.getConnection(DTLSConnector.java:1080)
        at org.eclipse.californium.scandium.DTLSConnector.send(DTLSConnector.java:2097)
        at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendRequest(CoapEndpoint.java:1004)
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendRequest(BaseCoapStack.java:231)
        at org.eclipse.californium.core.network.stack.ReliabilityLayer.sendRequest(ReliabilityLayer.java:107)
        at org.eclipse.californium.core.network.stack.BlockwiseLayer.sendRequest(BlockwiseLayer.java:323)
        at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69)
        at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69)
        at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer.sendRequest(ExchangeCleanupLayer.java:63)
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.sendRequest(BaseCoapStack.java:188)
        at org.eclipse.californium.core.network.stack.BaseCoapStack.sendRequest(BaseCoapStack.java:87)
        at org.eclipse.californium.core.network.CoapEndpoint$8.run(CoapEndpoint.java:816)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-12-01T15:31:06.759+0000 DEBUG connection: CID=14D696E231BF - /172.20.6.91:33735 added!
2020-12-01T15:31:06.759+0000 DEBUG Exchange[L1882] send request, failed transmissions: 0
2020-12-01T15:31:06.759+0000 TRACE connection: remove dtls-con: CID=C75AF130A632, /172.20.2.200:33735, ongoing handshake 5EA1E808E28B (size 848, left jobs: 0)
java.lang.Throwable: connection removed!
        at org.eclipse.californium.scandium.dtls.InMemoryConnectionStore.remove(InMemoryConnectionStore.java:532)
        at org.eclipse.californium.scandium.dtls.InMemoryConnectionStore.remove(InMemoryConnectionStore.java:523)
        at org.eclipse.californium.scandium.DTLSConnector.terminateConnection(DTLSConnector.java:1412)
        at org.eclipse.californium.scandium.DTLSConnector.processAlertRecord(DTLSConnector.java:1584)
        at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1330)
        at org.eclipse.californium.scandium.DTLSConnector$12.run(DTLSConnector.java:1195)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-12-01T15:31:06.759+0000 DEBUG handshake failed dtls-con: CID=C75AF130A632
org.eclipse.californium.scandium.dtls.HandshakeException: Received 'fatal alert'
        at org.eclipse.californium.scandium.DTLSConnector.processAlertRecord(DTLSConnector.java:1580)
        at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1330)
        at org.eclipse.californium.scandium.DTLSConnector$12.run(DTLSConnector.java:1195)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-12-01T15:31:06.759+0000 DEBUG Handshake with [/172.20.2.200:33735] has failed
2020-12-01T15:31:06.759+0000 DEBUG Exchange[L1882] prepare retransmission for CON-PUT    MID=   -1, Token=null, OptionSet={"Uri-Path":["5","0","1"], "Content-Format":"application/vnd.oma.lwm2m+tlv"},
d
```

client log (waakama client):
```
-> State: STATE_READY
128 bytes received from [192.168.1.152]:5684
16 FE FD 00  00 00 00 00  00 00 01 00  73 01 00 00   ............s...
67 00 01 00  00 00 00 00  67 FE FD 5F  BE 27 30 2F   g.......g.._.'0/
96 BF 72 9C  22 39 35 84  2C 24 24 6C  86 82 D2 79   ..r."95.,$$l...y
0A 8E 57 92  5B 23 55 C2  E8 9D 8C 20  9A 52 70 7C   ..W.[#U.... .Rp|
E0 AB 14 CC  A6 55 21 C7  BA 45 CE 51  E0 A0 45 F5   .....U!..E.Q..E.
82 D8 CD E6  BA 5A F7 A8  44 5A 4B 82  10 B7 AE E6   .....Z..DZK.....
09 88 CC 42  D8 87 3D AA  FD A0 32 0C  DA 00 02 C0   ...B..=...2.....
A8 02 00 00  00 0A 00 0D  00 06 00 04  04 03 04 01   ................

Nov 25 09:43:12 ALRT No security context for epoch: 0

Nov 25 09:43:12 WARN error updating security parameters

Nov 25 09:43:12 WARN error while handling handshake packet

error dtls handling message -552

error handling message -552`
```

any help is appreciated, Thanks!

**Comment by sbernard31** [comment]
Hi,

Could you give use more information.

- Which version of Leshan ?
- Which version of Wakaama ?
- Are you using demo/example or your own code based on those libraries ?
- Which DTLS library are you using with Wakaama ?
- Is you device behind a NAT ? (or any dynamic IP environment?)
- Are you using connection ID ? 
- How many clients ?
- Are your client hosted on the same machine ? (sharing same IP) 

Maybe a [wireshark/tcpdump capture/](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information) could help too.

**Comment by UnforgivenD** [comment]
thanks for reply.

1. Leshan 1.0.0
2. Wakaama v1.0
3. my own code based on libraries
4. tinyDtls 
5. no, its behind Load balancer - LVS
6. sorry, not sure what means connection id? is it some setting or tool?
7. goal is to perform tests in 50K clients, now failures about 300-500  of 2000 devices (with 2 leshan servers behind)
8. No, clients located in different machines (one machine have about 200 of clients with different ports).

**Comment by sbernard31** [comment]
(1) I advice to update to last `1.x` version (code SHOULD be backward compatible)
(5) So you are using Leshan in a cluster ? Did you face same issue when you are using only 1 server ?
(6) This is connection Id :https://tools.ietf.org/html/draft-ietf-tls-dtls-connection-id-08 (this can be useful when NAT is involved : [DTLS-1.2-connection-ID-bypassing-NATs](https://github.com/eclipse/californium/wiki/DTLS-1.2-connection-ID-bypassing-NATs) and [Using-Leshan-server-in-a-cluster](https://github.com/eclipse/leshan/wiki/Using-Leshan-server-in-a-cluster))

(9) does you client have fixed IP ?
(10) Are you using QueueMode ?
(11) You said you write data each 10 minutes but you have 2 servers so how do you device which server execute the write requests ?

A capture could definitely help.

**Comment by UnforgivenD** [comment]
thanks, issue was resolved with setting serverOnly=true in dtls configuration.
