### ISSUE TITLE
Unable to bootstrap to AVSystem's Coiote LwM2M stack.

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#986]
(from #984)

@jacintobarbeira :
> I'm trying out the AVSystem's Coiote LwM2M stack (both bootstrap and device management) using Leshan client demo.
When I connect the client to the bootstrap server, I get this error when the server sends back the device manager info to connect to:
```
2021-03-22 16:10:01,098 INFO LeshanClientDemo - Commands available :

  - create <objectId> : to enable a new object.
  - delete <objectId> : to disable a new object.
  - update : to trigger a registration update.
  - w : to move to North.
  - a : to move to East.
  - s : to move to South.
  - d : to move to West.

2021-03-22 16:10:01,098 INFO LeshanClient - Starting Leshan client ...
2021-03-22 16:10:01,103 INFO LeshanClient - Leshan client[endpoint:test-jb] started.
2021-03-22 16:10:01,103 INFO DefaultRegistrationEngine - Trying to start bootstrap session to coaps://lwm2m-test.avsystem.io:5694 ...
2021-03-22 16:10:01,812 INFO CaliforniumEndpointsManager - New endpoint created for server coaps://lwm2m-test.avsystem.io:5694 at coaps://0.0.0.0:64504
2021-03-22 16:10:01,835 INFO LeshanClientDemo - DTLS Full Handshake initiated by client : STARTED ...
2021-03-22 16:10:01,977 INFO LeshanClientDemo - DTLS Full Handshake initiated by client : SUCCEED
2021-03-22 16:10:02,220 INFO DefaultRegistrationEngine - Bootstrap started
2021-03-22 16:10:02,496 DEBUG Security - Write on Security resource /0/1/0
2021-03-22 16:10:02,497 DEBUG Security - Write on Security resource /0/1/1
2021-03-22 16:10:02,497 DEBUG Security - Write on Security resource /0/1/2
2021-03-22 16:10:02,497 DEBUG Security - Write on Security resource /0/1/3
2021-03-22 16:10:02,497 DEBUG Security - Write on Security resource /0/1/4
2021-03-22 16:10:02,497 DEBUG Security - Write on Security resource /0/1/5
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/0
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/1
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/2
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/3
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/4
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/5
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/10
2021-03-22 16:10:02,537 DEBUG Server - Write on Server resource /1/2/0
2021-03-22 16:10:02,537 DEBUG Server - Write on Server resource /1/2/1
2021-03-22 16:10:02,537 DEBUG Server - Write on Server resource /1/2/6
2021-03-22 16:10:02,537 DEBUG Server - Write on Server resource /1/2/7
2021-03-22 16:10:02,612 INFO DefaultRegistrationEngine - Bootstrap finished coaps://lwm2m-test.avsystem.io:5694.
2021-03-22 16:10:02,612 INFO DefaultRegistrationEngine - Unable to send Bootstrap request : null
2021-03-22 16:10:02,613 ERROR DefaultRegistrationEngine - Unexpected exception during bootstrap task
java.lang.NullPointerException
	at org.eclipse.leshan.client.object.Security.read(Security.java:244)
	at org.eclipse.leshan.client.resource.BaseInstanceEnabler.read(BaseInstanceEnabler.java:118)
	at org.eclipse.leshan.client.resource.ObjectEnabler.doRead(ObjectEnabler.java:201)
	at org.eclipse.leshan.client.resource.BaseObjectEnabler.read(BaseObjectEnabler.java:173)
	at org.eclipse.leshan.client.servers.ServersInfoExtractor.getInfo(ServersInfoExtractor.java:69)
	at org.eclipse.leshan.client.servers.ServersInfoExtractor.getBootstrapServerInfo(ServersInfoExtractor.java:150)
	at org.eclipse.leshan.client.engine.DefaultRegistrationEngine.scheduleClientInitiatedBootstrap(DefaultRegistrationEngine.java:493)
	at org.eclipse.leshan.client.engine.DefaultRegistrationEngine.access$500(DefaultRegistrationEngine.java:74)
	at org.eclipse.leshan.client.engine.DefaultRegistrationEngine$ClientInitiatedBootstrapTask.run(DefaultRegistrationEngine.java:524)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-03-22 16:10:02,614 INFO LeshanClient - Destroying Leshan client ...
2021-03-22 16:10:02,616 INFO LeshanClient - Leshan client destroyed.
```

**Comment by sbernard31** [comment]
Just to be sure you are using **leshan-client-demo** at client side and  **AVSystem's Coiote LwM2M stack** at server and bootstrap server side ?

Looking at the log.
I guess that at bootstrap time the server write data for 1 bootstrap server : 
```
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/0
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/1
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/2
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/3
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/4
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/5
2021-03-22 16:10:02,498 DEBUG Security - Write on Security resource /0/2/10
2021-03-22 16:10:02,537 DEBUG Server - Write on Server resource /1/2/0
2021-03-22 16:10:02,537 DEBUG Server - Write on Server resource /1/2/1
2021-03-22 16:10:02,537 DEBUG Server - Write on Server resource /1/2/6
2021-03-22 16:10:02,537 DEBUG Server - Write on Server resource /1/2/7
```
and  1 bootstrap server : 
```
2021-03-22 16:10:02,496 DEBUG Security - Write on Security resource /0/1/0
2021-03-22 16:10:02,497 DEBUG Security - Write on Security resource /0/1/1
2021-03-22 16:10:02,497 DEBUG Security - Write on Security resource /0/1/2
2021-03-22 16:10:02,497 DEBUG Security - Write on Security resource /0/1/3
2021-03-22 16:10:02,497 DEBUG Security - Write on Security resource /0/1/4
2021-03-22 16:10:02,497 DEBUG Security - Write on Security resource /0/1/5
```
(I guess this one is the bootstrap server because there is no write on resource /0/?/10)

**Looking at the code of Leshan I found that :**

1.  Leshan does not behave correctly when resource 10 is missing on object instance 0.
=> I double checked the specification and this is a bug. I will fix it.

2. But I guess it will have another issue for now **leshan-client** has a limitation it does not allow to remove the bootstrap server.
Which is by default the instance 0 of the security object 0 ("/0/0") and as you try to write boostrap server on "/0/1" that means that at the end you will have 2 bootstrap server. 
=> to handle this correctly this is more than a bug fix probably and so will take more time.

So wait for the bug fix 1) and we will see how it behave.
For 2) I will think about this but will not be able to implement this quickly, Could you configure  you bootstrap server to write the bootstrap security instance on "/0/0" ? This could be a workaround at short term.

**Comment by sbernard31** [comment]
I create a dedicated issue for #987 and a PR (#988) to fix it.

**Comment by jacintobarbeira** [comment]
These are the logs from the Coiote bootstrap server (redacted id and psk):
```
2021.03.22 17:10:03.796 INFO  [TASK] Set: LwM2M Security.1.LwM2M Server URI=coaps://lwm2m-test.avsystem.io:5694
2021.03.22 17:10:03.796 INFO  [TASK] Set: LwM2M Security.1.Security Mode=0
2021.03.22 17:10:03.796 INFO  [TASK] Set: LwM2M Security.1.Public Key or Identity=redacted
2021.03.22 17:10:03.796 INFO  [TASK] Set: LwM2M Security.1.Secret Key=redacted
2021.03.22 17:10:03.796 INFO  [TASK] Set: LwM2M Security.1.Server Public Key=
2021.03.22 17:10:03.797 INFO  [TASK] Set: LwM2M Security.1.Bootstrap-Server=true
2021.03.22 17:10:03.801 INFO  [TASK] Set: LwM2M Security.2.LwM2M Server URI=coaps://lwm2m-test.avsystem.io:5684
2021.03.22 17:10:03.801 INFO  [TASK] Set: LwM2M Security.2.Security Mode=0
2021.03.22 17:10:03.801 INFO  [TASK] Set: LwM2M Security.2.Public Key or Identity=redacted
2021.03.22 17:10:03.801 INFO  [TASK] Set: LwM2M Security.2.Secret Key=redacted
2021.03.22 17:10:03.801 INFO  [TASK] Set: LwM2M Security.2.Server Public Key=
2021.03.22 17:10:03.801 INFO  [TASK] Set: LwM2M Security.2.Bootstrap-Server=false
2021.03.22 17:10:03.801 INFO  [TASK] Set: LwM2M Security.2.Short Server ID=1
2021.03.22 17:10:03.801 INFO  [TASK] Set: LwM2M Server.2.Short Server ID=1
2021.03.22 17:10:03.801 INFO  [TASK] Set: LwM2M Server.2.Lifetime=60
2021.03.22 17:10:03.801 INFO  [TASK] Set: LwM2M Server.2.Notification Storing When Disabled or Offline=false
```

It seems it is trying to reconfigure bootstrap access and adding the actual LwM2M server.

**Comment by sbernard31** [comment]
This confirms my guess.
The PR #988 should help a little bit but after the bootstrap session you will have 2 bootstrap server configured and so behavior could be unexpected.

I will work on the 2nd part of this issue  but I will not able to provide a fix quickly.

Are you able to configure your server to write instance /0/0 (LwM2M Security.0) instead of /0/2 (LwM2M Security.2) ?

**Comment by jacintobarbeira** [comment]
I'll talk to the AV System's guys. I'm using the defaults.

**Comment by jacintobarbeira** [comment]
Anyway, just retested with the latest fix from #987 and it worked like a charm.
thanks for the quick turnaround.

**Comment by sbernard31** [comment]
I looked again at the specification and it says : 

> The LwM2M Client MUST have at most one LwM2M Bootstrap-Server Account.

(source :[core§Bootstrap-Information](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-1-2-0-612-Bootstrap-Information))

> Only in the Bootstrap Interface, the "Bootstrap-Delete" operation MAY target any Instance or all Instances of any Object including the Security Object (ID:0), supported by the LwM2M Client. The two exceptions are the LwM2M Bootstrap-Server Account, potentially including an associated Instance of an OSCORE Object ID:21, and the single Instance of the mandatory Device Object (ID:3), which are not affected by any Delete operation.

(source : [core§Bootstrap-Delete-Operation](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-1-7-6-0-6176-Bootstrap-Delete-Operation))

The **leshan-client-demo** bootstrap server security instance is 0. (/0/0)
I guess your bootstrap server deletes at least object /0 and /1. (a wireshark capture could confirms this)

But /0/0 is not deleted because this is the  LwM2M Bootstrap-Server Account. (c.f. bootstrap delete request description)
Then your server write a new LwM2M Bootstrap-Server Account as instance 2 of the Security Object.

Meaning at the end there is 2 bootstrap server which does not respect : _"The LwM2M Client MUST have at most one LwM2M Bootstrap-Server Account."_

The client should answer to bootstrap finished with an error as explained in : 

> When a Bootstrap Information is loaded in the LwM2M Client, any detected inconsistency MUST be reported in sending an error response code to the Bootstrap-Finish operation.

(source [core§Bootstrap-and-Configuration-Consistency](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-1-6-0-616-Bootstrap-and-Configuration-Consistency)

**Comment by sbernard31** [comment]
> Anyway, just retested with the latest fix from #987 and it worked like a charm.

@jacintobarbeira, so it works but mainly because **leshan-client** does not check the bootstrap information consistency.

This is something that I will probably add at short or mid term. With this new feature in your case you should receive a `4.06 Not Acceptable Inconsistent loaded configuration` on Bootstrap finished. 

So I encourage you to :
 -  find a way to configure your bootstrap server correctly.
 - OR to report this to AV System's guys (they can discuss about this with us here if needed)

HTH :slightly_smiling_face:

**Comment by sbernard31** [comment]
I was pretty sure that by the past instance /0/0 was dedicated to bootstrap server but wasn't able to find it in the specification. 
This is a change between 1.0.0 and 1.0.1 ( see https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/245#issuecomment-346202665).

I will try to get more information from OMA.

**Comment by sbernard31** [comment]
I created a dedicated issue for bootstrap config consistency check : #1000
